/**
 * Voice bank schema for combat banter.
 * Every creature MUST supply all fields — no Mad Lib fallback.
 *
 * @typedef {[string, string]} Pair
 * @typedef {{
 *   open: Pair[],
 *   hit: Pair[],
 *   hitBloodied: Pair[],
 *   miss: Pair[],
 *   crit: Pair[],
 *   kits: Record<string, Pair>,
 *   kitGeneric: Pair,
 *   kitRan: Pair,
 *   hcritRan: Pair,
 *   mHit: Pair,
 *   mHitBloodied: Pair,
 *   mMiss: Pair,
 *   winded: Pair,
 *   bruised: Pair,
 *   bloodied: Pair,
 *   heartWound: Pair,
 *   run: Pair,
 *   runAgain: Pair,
 *   chase: Pair,
 *   chase2: Pair,
 *   close: Pair,
 *   closeSmoke: Pair,
 *   victory: Pair,
 *   victoryHealed: Pair,
 *   victoryKited: Pair,
 *   victoryCrit: Pair,
 *   victoryNet: Pair,
 *   defeat: Pair,
 *   defeatCrit: Pair,
 *   defeatRan: Pair,
 *   defeatHeal: Pair,
 * }} VoiceBank
 */
export const KITS = [
  'poison',
  'alchemists-fire',
  'caltrops',
  'acid-vial',
  'holy-water',
  'smokestick',
  'hunting-trap',
  'net',
  'healing-potion',
  'oil-flask',
];

export const META = [
  { id: 'patches', name: 'Patches', vibe: 'ancient scavenger temp who bills love in scrap metal', pronouns: 'I' },
  { id: 'dumpster-king', name: 'Dumpster King', vibe: 'regal waste sovereign; smell is the crown', pronouns: 'I' },
  { id: 'bleed-static', name: 'Bleed Static', vibe: 'intimate predator romanticizing unused PTO', pronouns: 'I' },
  { id: 'proxy-bit', name: 'Proxy Bit', vibe: 'expired-clearance courier who delivers bites like memos', pronouns: 'I' },
  { id: 'glasswing', name: 'Glasswing', vibe: 'transparent heart-reader who grades your soul mid-fight', pronouns: 'I' },
  { id: 'patchwire', name: 'Patchwire', vibe: 'crumb parliament that votes with teeth', pronouns: 'we' },
  { id: 'clickers', name: 'Clickers', vibe: 'night-shift hospitality bats who tip in blood', pronouns: 'we' },
  { id: 'crow-ledger', name: 'Crow Ledger', vibe: 'citation ravens who balance books in pecking', pronouns: 'we' },
  { id: 'scale-crew', name: 'Scale Crew', vibe: 'tiny trap apprentices yelling for a boss who may not care', pronouns: 'we' },
  { id: 'drain-gang', name: 'Drain Gang', vibe: 'ankle-tax franchise rats with landlord energy', pronouns: 'we' },
  { id: 'amber-silk', name: 'Amber Silk', vibe: 'LP spider who wraps shrinkage like intimacy', pronouns: 'I' },
  { id: 'veinrot', name: 'Veinrot', vibe: 'cold-storage zombie who never clocks out', pronouns: 'I' },
  { id: 'drool', name: 'Drool', vibe: 'cute contract devil trading souls for snacks', pronouns: 'I' },
  { id: 'rattlewire', name: 'Rattlewire', vibe: 'punctual bones who reschedule your spine', pronouns: 'I' },
  { id: 'chrome-edge', name: 'Chrome Edge', vibe: 'living floor-model sword with warranty rage', pronouns: 'I' },
  { id: 'the-choir', name: 'The Choir', vibe: 'forced-fun spirits who sing what you bury', pronouns: 'we' },
  { id: 'neon-howl', name: 'Neon Howl', vibe: 'pack chase braid on wet neon — WE hunt', pronouns: 'we' },
  { id: 'hexhive', name: 'Hexhive', vibe: 'IT tickets with legs; patch notes arrive as bites', pronouns: 'we' },
  { id: 'scrap-mob', name: 'Scrap Mob', vibe: 'union goblins who surround scabs on principle', pronouns: 'we' },
  { id: 'marrow-gang', name: 'Marrow Gang', vibe: 'skeleton drill team that kept formation', pronouns: 'we' },
  { id: 'grin', name: 'Grin', vibe: 'mimic puddle with sticky claim manners', pronouns: 'I' },
  { id: 'sister-static', name: 'Sister Static', vibe: 'dead-air radio glamour on Channel 7', pronouns: 'I' },
  { id: 'knuckle', name: 'Knuckle', vibe: 'ogre who closes tickets with axes not words', pronouns: 'I' },
  { id: 'pose-soft', name: 'Pose Soft', vibe: 'gorgon visual merch who freezes beauty into brand', pronouns: 'I' },
  { id: 'oxidize', name: 'Oxidize', vibe: 'rust monster who loves metal more than you', pronouns: 'I' },
  { id: 'iron-cadre', name: 'Iron Cadre', vibe: 'hobgoblin line officers who advance in silence', pronouns: 'we' },
  { id: 'laugh-track', name: 'Laugh Track', vibe: 'hyena studio audience that eats screams', pronouns: 'we' },
  { id: 'silt-knives', name: 'Silt Knives', vibe: 'cold-blooded knife fish who clean runoff with blades', pronouns: 'we' },
  { id: 'cinder-crew', name: 'Cinder Crew', vibe: 'magma mephits who ignite on read', pronouns: 'we' },
  { id: 'sting-grid', name: 'Sting Grid', vibe: 'wasp pack that denies altitude permits with stings', pronouns: 'we' },
];
