/** @type {Record<string, any>} */
export const BATCH4 = {
  'proxy-bit': {
    open: [
      [`Sealed envelope. Nervous system. Do not reply-all. Do not pet.`, `Legal already liked this sentence and forwarded it somewhere you'll never clear.`],
      [`Delivery for you. Package is teeth. Tracking: your throat.`, `A master to disappoint. A hunter to sample. CC me on both.`],
      [`Telepathy. A bite the size of a period. Loyalty still on the payroll — expired clearance and all.`, `Antimagic. "Cute toy." Read receipts. "Circle back." — turn-offs. You look like none. Sign here.`],
      [`Shocking honesty: secrets small enough to fit on a windowsill are my love language.`, `Sweet handshake optional. I bite cute. Sign for delivery before you flinch.`],
    ],
    hit: [
      [`You scratched the courier. Rude mid-delivery.`, `That one had feelings. Legal resentments pending.`],
      [`Proxy took a nick. Seal still holds.`, `Ow. The envelope remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking. Keep signing — tracking updates live.`, `Bloodied courier. Still sealed. Still biting.`],
    ],
    miss: [
      [`Missed the package. Delivery continues.`, `Air through Cubicle 4B. Try again with intent — or sign.`],
      [`You swung at Interoffice Courier and hit a memo. Memos bite back.`, `Miss logged. Route unchanged.`],
    ],
    crit: [
      [`That one tore the seal. Emotionally. And also actually.`, `Crit on a courier? Someone in Legal just flinched in a CC.`],
      [`Okay. Soft spot under the clearance. Dangerous sampling.`, `You found the nervous system under the envelope. Keep going — I'm listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a bite the size of a period.`, `Toxin on courier-adjacent dates. Cute. My blood quit with the clearance.`],
      'alchemists-fire': [`Flask hits. Cubicle blooms. Fire voids the chain of custody.`, `Arson mid-delivery. Hot. Illegal. Intimate. Still sealed.`],
      caltrops: [`Iron teeth. Ankles on the menu. I fly for a living.`, `You seeded spite. Couriers walk it on windowsills.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under cubicle honesty.`, `Chemistry thrown like a drink on a delivery. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a construct smells like panic and bleach.`, `Church water on a courier. The dead hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your secrets through the haze.`, `You hid mid-delivery. Couriers find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a memo. Irony is a tracking number.`, `Bear-trap for cubicle prey. I invented commitment issues with seals.`],
      net: [`Mesh on a courier. Commitment layered on clearance. Flail is the signature.`, `You bagged the package. Bold. Legal is laughing somewhere.`],
      'healing-potion': [`Red sip. Juice for hunters who plan to live. I prefer you rare and sampled.`, `Healing mid-delivery. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Seals slip for no one.`, `Slippery warfare in 4B. Career move for a reply-all.`],
    },
    kitGeneric: [`You opened the bag mid-delivery. That's a write-up in Legal.`, `Props. Theater kid. Couriers grade performances in bites.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Tracking noticed.`, `Flee, then kit. Clearance grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my seal.`, `Runner with a finishing move. Impressed. Offended. Still delivering.`],
    mHit: [`Bite applied. Don't look surprised — you matched first.`, `That's for the unread memo and the petting you promised.`],
    mHitBloodied: [`Bloodied and still landing. Telepathy talks.`, `I'm hurt. You're hurt more. Fair trade in periods.`],
    mMiss: [`Missed. Don't get cocky — the route is still circling.`, `Lucky. Luck expires when couriers get bored.`],
    winded: [`First scratch on the seal. Don't get attached.`, `That tickled. Upgrade your intent or sign properly.`],
    bruised: [`Color coming in under construct. Keep painting.`, `Mid-delivery damage. Persistent — like a bad read receipt.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Delivery continues.`, `Bloodied courier. Finish it or become décor on a windowsill.`],
    heartWound: [`That one landed on something soft under the clearance I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and forwardable.`],
    run: [`Flee 4B? I invented chase as a route.`, `Break contact? Deliveries don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no signature.`, `You ran twice. Tracking logged it. Chase is custody.`],
    chase: [`You ran twice. Chase is how couriers collect signatures.`, `Second flee. I'm billing cardio in memos.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in CC.`, `Second chase. Prey with a fitness plan and no clearance left.`],
    close: [`Back in your face. Miss the bite?`, `Range ends. Soft period resumes. Cubicle hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still sealed.`, `Smoke fades. Soft bite resumes. Miss the package?`],
    victory: [`Courier down. Keep the seal. Don't keep the smug.`, `You won. Don't ghost my ghost — Legal remembers.`],
    victoryHealed: [`You juiced and still took the delivery. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in 4B. Optimistic hunter with a receipt.`],
    victoryKited: [`You kited a courier. Route wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime in tracking.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the seal.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Hunter down. Delivery updated. Seal's still mine — sample pending.`, `Verified snack. Cubicle solved. Your bag was mid.`],
    defeatCrit: [`You crit the courier and still died. Talent without a signature.`, `Crit energy, snack ending. Classic memo romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Tracking writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Sign next time.`],
  },

  glasswing: {
    open: [
      [`I read the want behind your eyes. It failed the values survey.`, `Fight me anyway — honesty looks better with a scratch, and I keep score in mirrors.`],
      [`A pulse with a conscience. Rare stock on this floor. Someone who flinches at truth and stays.`, `Heart sight. Sleep arrows. Opinions you didn't request. 360 feedback.`],
      [`Fiends. Liars. People who skip aftercare. Self-described "team players" — turn-offs. You look messy. Promising.`, `Conspiracy of glass: every reflection here is taking notes for someone who never clocks out.`],
      [`Shocking honesty: if your want passes, I might stay visible.`, `Sweet of you to thrash without being asked. Keep thrashing. The arcade likes the score.`],
    ],
    hit: [
      [`You scratched the audit. Rude mid-survey.`, `That one had feelings. Values resentments pending.`],
      [`Auditor took a nick. Mirror still holds.`, `Ow. The glass remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking light. Keep thrashing — score updates live.`, `Bloodied auditor. Still judging. Still visible — for now.`],
    ],
    miss: [
      [`Missed the truth. Survey continues.`, `Air through Mirror Arcade. Try again with intent — or honesty.`],
      [`You swung at Culture & Values and hit a reflection. Reflections bite back.`, `Miss logged. Score unchanged.`],
    ],
    crit: [
      [`That one tore the survey. Emotionally. And also actually.`, `Crit on an auditor? Someone in the annex just flinched in glass.`],
      [`Okay. Soft spot under the heart sight. Dangerous honesty.`, `You found the want under the score. Keep going — I'm listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned an auditor who grades chemistry.`, `Toxin on mirror-adjacent dates. Cute. My blood quit caring about liars.`],
      'alchemists-fire': [`Flask hits. Arcade blooms. Fire hates glass — I hate fire more.`, `Arson mid-survey. Hot. Illegal. Intimate. Still scoring.`],
      caltrops: [`Iron teeth. Ankles on the menu. I float for a living.`, `You seeded spite. Auditors walk it in mirrors.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under fluorescent honesty.`, `Chemistry thrown like a drink on a values survey. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in an HR annex smells like panic and bleach.`, `Church water on fey. The dead hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still see your want through the haze.`, `You hid mid-survey. Heart sight finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped an auditor. Irony is a PIP.`, `Bear-trap for arcade prey. I invented commitment issues with mirrors.`],
      net: [`Mesh on glass. Commitment layered on visibility. Flail is the score.`, `You bagged the auditor. Bold. The reflection is laughing.`],
      'healing-potion': [`Red sip. Juice for pulses who plan to live. I prefer you rare and honest.`, `Healing mid-survey. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Mirrors slip for no one.`, `Slippery warfare in the arcade. Career move for a liar.`],
    },
    kitGeneric: [`You opened the bag mid-survey. That's a write-up in glass.`, `Props. Theater kid. Auditors grade performances in wants.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Score noticed.`, `Flee, then kit. Values grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my survey.`, `Runner with a finishing move. Impressed. Offended. Still scoring.`],
    mHit: [`Arrow applied. Don't look surprised — you matched first.`, `That's for the unread want and the flinch you promised.`],
    mHitBloodied: [`Bloodied and still landing. Honesty talks.`, `I'm hurt. You're hurt more. Fair trade in mirrors.`],
    mMiss: [`Missed. Don't get cocky — the glass is still circling.`, `Lucky. Luck expires when auditors get bored.`],
    winded: [`First scratch on the score. Don't get attached.`, `That tickled. Upgrade your intent or tell the truth.`],
    bruised: [`Color coming in under glass. Keep painting.`, `Mid-survey damage. Persistent — like a bad team player.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Score continues.`, `Bloodied auditor. Finish it or become décor in the annex.`],
    heartWound: [`That one landed on something soft under the heart sight I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and almost passing.`],
    run: [`Flee the arcade? I invented chase in reflections.`, `Break contact? Surveys don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and a failed want.`, `You ran twice. The mirror logged it. Chase is aftercare.`],
    chase: [`You ran twice. Chase is how auditors collect truth.`, `Second flee. I'm billing cardio in scores.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in glass.`, `Second chase. Prey with a fitness plan and no conscience left.`],
    close: [`Back in your face. Miss the score?`, `Range ends. Soft arrows resume. Arcade hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still visible.`, `Smoke fades. Soft arrows resume. Miss the survey?`],
    victory: [`Auditor down. Keep the mirror. Don't keep the smug.`, `You won. Don't ghost my ghost — the glass remembers.`],
    victoryHealed: [`You juiced and still took the score. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in the arcade. Optimistic pulse with a receipt.`],
    victoryKited: [`You kited Culture & Values. Honesty undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime in mirrors.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the want.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Pulse down. Score updated. Glass still mine — want pending.`, `Verified snack. Arcade solved. Your bag was mid.`],
    defeatCrit: [`You crit the auditor and still died. Talent without a conscience.`, `Crit energy, snack ending. Classic mirror romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Reflections write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Stay for the mirror next time.`],
  },

  'crow-ledger': {
    open: [
      [`We tally sins on the railing, then collect in pecks. Net-30.`, `Lost the receipt? That's a late fee with feathers and a gossip trail.`],
      [`Guilty faces. Shiny rings. Open windows. Tickets still bleeding red.`, `Numbers. Beaks. A ledger you can't audit back. Interest.`],
      [`Scarecrows. Closed blinds. Off-key whistling. "I lost the receipt." — turn-offs. You look guilty. Perfect.`, `Books don't balance themselves. Neither do you. Rails. Beaks. Forever.`],
      [`Shocking honesty: we want sins we can tally on the rail. Heartstring: we tally because no one else will.`, `Sweet of you to thrash without being asked. Keep thrashing. The spire likes the gossip.`],
    ],
    hit: [
      [`You scratched the ledger. Rude mid-tally.`, `That one had feelings. Compliance resentments pending.`],
      [`Flock took a nick. Balance still holds.`, `Ow. The railing remembers. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep sinning — tally updates live.`, `Bloodied flock. Still counting. Still pecking.`],
    ],
    miss: [
      [`Missed the books. Tally continues.`, `Air through Parking Spire. Try again with intent — or a receipt.`],
      [`You swung at Compliance and hit a citation. Citations bite back.`, `Miss logged. Ledger unchanged.`],
    ],
    crit: [
      [`That one tore the balance. Emotionally. And also actually.`, `Crit on the flock? Someone on the cornice just flinched in gossip.`],
      [`Okay. Soft spot under the pecking. Dangerous auditing.`, `You found the interest under the numbers. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a flock that pecks first.`, `Toxin on rail-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Spire blooms. Fire hates ledgers — we hate fire more.`, `Arson mid-tally. Hot. Illegal. Intimate. Still counting.`],
      caltrops: [`Iron teeth. Ankles on the menu. We prefer cornices.`, `You seeded spite. Flocks walk it in feathers.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under quarterly honesty.`, `Chemistry thrown like a drink on a citation. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a railing smells like panic and bleach.`, `Church water on ravens. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your guilt through the haze.`, `You hid mid-tally. Flocks find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a ledger. Irony is a late fee.`, `Bear-trap for spire prey. We invented commitment issues with receipts.`],
      net: [`Mesh on a flock. Commitment layered on feathers. Flail is the interest.`, `You bagged compliance. Bold. The gossip is laughing.`],
      'healing-potion': [`Red sip. Juice for sinners who plan to live. We prefer you rare and guilty.`, `Healing mid-tally. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Keys hit concrete anyway.`, `Slippery warfare on the spire. Career move for a lost receipt.`],
    },
    kitGeneric: [`You opened the bag mid-tally. That's a write-up in feathers.`, `Props. Theater kid. Compliance grades performances in pecks.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Late fee.`, `Flee, then kit. Ledgers grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our tally.`, `Runner with a finishing move. Impressed. Offended. Still collecting.`],
    mHit: [`Peck applied. Don't look surprised — you matched first.`, `That's for the unread citation and the guilt you promised.`],
    mHitBloodied: [`Bloodied and still landing. Numbers talk.`, `We're hurt. You're hurt more. Fair trade in interest.`],
    mMiss: [`Missed. Don't get cocky — the flock is still circling.`, `Lucky. Luck expires when ledgers get bored.`],
    winded: [`First scratch on the balance. Don't get attached.`, `That tickled. Upgrade your intent or produce a receipt.`],
    bruised: [`Color coming in under feather. Keep painting.`, `Mid-tally damage. Persistent — like a bad quarterly.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Tally continues.`, `Bloodied flock. Finish it or become décor on the railing.`],
    heartWound: [`That one landed on something soft under the gossip we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and countable.`],
    run: [`Flee the spire? We invented chase as collection.`, `Break contact? Ledgers don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and a lost receipt.`, `You ran twice. The tally logged it. Chase is Net-30.`],
    chase: [`You ran twice. Chase is how flocks collect interest.`, `Second flee. We're billing cardio in pecks.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in feathers.`, `Second chase. Prey with a fitness plan and no receipt left.`],
    close: [`Back in your face. Miss the tally?`, `Range ends. Soft beaks resume. Flock hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still counting.`, `Smoke fades. Soft beaks resume. Miss the citation?`],
    victory: [`Flock down. Keep the ledger. Don't keep the smug.`, `You won. Don't ghost our ghost — the railing remembers.`],
    victoryHealed: [`You juiced and still took the tally. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory on the spire. Optimistic sinner with a receipt.`],
    victoryKited: [`You kited Compliance. Ledger wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a late fee.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the sins.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Sinner down. Tally updated. Balance still ours — guilt pending.`, `Verified snack. Spire solved. Your bag was mid.`],
    defeatCrit: [`You crit the flock and still died. Talent without a receipt.`, `Crit energy, snack ending. Classic railing romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Gossip writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Keep the receipt next time.`],
  },

  'scale-crew': {
    open: [
      [`We are small. The springs are not. Kneepads "suggested."`, `We yell for the boss like a joke until the plate clicks and it isn't.`],
      [`Someone tall enough to test the plates. Mentors who don't mind unpaid. A body that survives the click.`, `Pack tactics. Slings. Unhealthy dragon fandom. Safety waivers.`],
      [`Sunlight. Lone wolves. People who kick traps first. OSHA with a clipboard — turn-offs. You look tall. Perfect.`, `Sweet of you to watch your step. Watching is the romance. Stepping is the lesson.`],
      [`Shocking honesty: tunnels. Cheese. Yelling in formation. The click before the drop — that's our love song.`, `Complex apology incoming from someone who may not care. Sign the waiver.`],
    ],
    hit: [
      [`You scratched the apprentices. Rude mid-drill.`, `That one had feelings. Trap resentments pending.`],
      [`Crew took a nick. Springs still hold.`, `Ow. The plates remember. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep testing — click updates live.`, `Bloodied apprentices. Still yelling. Still small.`],
    ],
    miss: [
      [`Missed the crew. Drill continues.`, `Air through Trap Wing. Try again with intent — or step wrong.`],
      [`You swung at Facilities apprentices and hit a spring. Springs bite back.`, `Miss logged. Plate unchanged.`],
    ],
    crit: [
      [`That one tore the formation. Emotionally. And also actually.`, `Crit on the crew? Someone in the tunnel just flinched for the boss.`],
      [`Okay. Soft spot under the kneepads. Dangerous mentoring.`, `You found the fear under the yell. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned apprentices who practice first.`, `Toxin on trap-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Wing blooms. Fire hates springs — we hate fire more.`, `Arson mid-drill. Hot. Illegal. Intimate. Still yelling.`],
      caltrops: [`Iron teeth. Ankles on the menu — we respect the craft.`, `You seeded spite. Apprentices walk it in formation.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under tunnel honesty.`, `Chemistry thrown like a drink on a waiver. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in Trap Wing smells like panic and bleach.`, `Church water on kobolds. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your height through the haze.`, `You hid mid-drill. Crews find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped trap apprentices. Irony is a plate click.`, `Bear-trap for wing prey. We invented commitment issues with springs.`],
      net: [`Mesh on small bodies. Commitment layered on yells. Flail is the waiver.`, `You bagged the crew. Bold. The boss might care. Might not.`],
      'healing-potion': [`Red sip. Juice for testers who plan to live. We prefer you rare and tall.`, `Healing mid-drill. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Plates slip for no one.`, `Slippery warfare in Trap Wing. Career move for a lone wolf.`],
    },
    kitGeneric: [`You opened the bag mid-drill. That's a write-up in cheese.`, `Props. Theater kid. Apprentices grade performances in clicks.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Boss noticed? Maybe.`, `Flee, then kit. Springs grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our yell.`, `Runner with a finishing move. Impressed. Offended. Still small.`],
    mHit: [`Sling applied. Don't look surprised — you matched first.`, `That's for the unread waiver and the step you promised.`],
    mHitBloodied: [`Bloodied and still landing. Formation talks.`, `We're hurt. You're hurt more. Fair trade in cheese.`],
    mMiss: [`Missed. Don't get cocky — the crew is still circling.`, `Lucky. Luck expires when apprentices get bored.`],
    winded: [`First scratch on the yell. Don't get attached.`, `That tickled. Upgrade your intent or sign the waiver.`],
    bruised: [`Color coming in under scale. Keep painting.`, `Mid-drill damage. Persistent — like a bad OSHA visit.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Drill continues.`, `Bloodied crew. Finish it or become décor on the plate.`],
    heartWound: [`That one landed on something soft under the dragon fandom we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and mentor-shaped.`],
    run: [`Flee Trap Wing? We invented chase as a yell.`, `Break contact? Drills don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and height.`, `You ran twice. The plate logged it. Chase is practice.`],
    chase: [`You ran twice. Chase is how apprentices collect mentors.`, `Second flee. We're billing cardio in yells.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in clicks.`, `Second chase. Prey with a fitness plan and no kneepads left.`],
    close: [`Back in your face. Miss the click?`, `Range ends. Soft slings resume. Crew hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still yelling.`, `Smoke fades. Soft slings resume. Miss the plate?`],
    victory: [`Crew down. Keep the waiver. Don't keep the smug.`, `You won. Don't ghost our ghost — the springs remember.`],
    victoryHealed: [`You juiced and still took the drill. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Trap Wing. Optimistic tester with a receipt.`],
    victoryKited: [`You kited the apprentices. Spring wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in cheese.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the click.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Tester down. Drill updated. Yell's still ours — click pending.`, `Verified snack. Wing solved. Your bag was mid.`],
    defeatCrit: [`You crit the crew and still died. Talent without a waiver.`, `Crit energy, snack ending. Classic tunnel romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Plates write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Watch your step next time.`],
  },

  veinrot: {
    open: [
      [`Still walking. Still hungry. Still better company than your last all-hands.`, `My name tag outlived the people who printed it and the freezer that forgot me.`],
      [`Brains optional. Pulse preferred. Overtime that doesn't ask.`, `Cold hands. Commitment. The smell of forever. A badge that won't die.`],
      [`Radiant damage. Pep talks. Open caskets. "Synergy standups." — turn-offs. You look like company. Promising.`, `Loneliness freezes slower than meat. Come close — cold storage hugs harder.`],
      [`Shocking honesty: Undead Fortitude is just refusing to clock out. You'll outlast nothing.`, `Sweet of you to thrash without being asked. Keep thrashing. The freezer likes the silence.`],
    ],
    hit: [
      [`You scratched forever. Rude mid-shift.`, `That one had feelings. Cold resentments pending.`],
      [`Associate took a nick. Badge still holds.`, `Ow. The freezer remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking cold. Keep walking — shift updates live.`, `Bloodied and still on shift. That's not tenure. That's refusal.`],
    ],
    miss: [
      [`Missed the forever. Shift continues.`, `Air through Cold Storage. Try again with intent — or stay warm.`],
      [`You swung at Eternal Associate and hit a nametag. Nametags bite back.`, `Miss logged. Freezer unchanged.`],
    ],
    crit: [
      [`That one tore the badge. Emotionally. And also actually.`, `Crit on forever? Someone in cold storage just flinched in meat.`],
      [`Okay. Soft spot under the cold. Dangerous company.`, `You found the loneliness under the hunger. Keep going — I'm listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned forever. Chemistry is late.`, `Toxin on freezer-adjacent dates. Cute. My blood quit with the warmth.`],
      'alchemists-fire': [`Flask hits. Freezer blooms. Fire hates cold — I hate fire more.`, `Arson mid-shift. Hot. Illegal. Intimate. Still walking.`],
      caltrops: [`Iron teeth. Ankles on the menu. I walk long darks.`, `You seeded spite. Forever walks it cold.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under freezer honesty.`, `Chemistry thrown like a drink on a nametag. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on forever smells like panic and bleach — radiant-adjacent. Hard no.`, `Church water on a zombie. The living hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your pulse through the haze.`, `You hid mid-shift. Forever finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped forever. Irony is a schedule conflict.`, `Bear-trap for freezer prey. I invented commitment issues with badges.`],
      net: [`Mesh on forever. Commitment layered on cold. Flail is the overtime.`, `You bagged the associate. Bold. The nametag is laughing.`],
      'healing-potion': [`Red sip. Juice for pulses who plan to live. I prefer you rare and company.`, `Healing mid-shift. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Cold slips for no one.`, `Slippery warfare in Cold Storage. Career move for a pep talk.`],
    },
    kitGeneric: [`You opened the bag mid-shift. That's a write-up in forever.`, `Props. Theater kid. Associates grade performances in silence.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Freezer noticed.`, `Flee, then kit. Forever grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my badge.`, `Runner with a finishing move. Impressed. Offended. Still walking.`],
    mHit: [`Cold applied. Don't look surprised — you matched first.`, `That's for the unread overtime and the company you promised.`],
    mHitBloodied: [`Bloodied and still landing. Commitment talks.`, `I'm hurt. You're hurt more. Fair trade in forever.`],
    mMiss: [`Missed. Don't get cocky — the cold is still circling.`, `Lucky. Luck expires when forever gets bored.`],
    winded: [`First scratch on the badge. Don't get attached.`, `That tickled. Upgrade your intent or stay for the dark walk.`],
    bruised: [`Color coming in under cold. Keep painting.`, `Mid-shift damage. Persistent — like a bad all-hands.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Shift continues.`, `Bloodied associate. Finish it or become décor in the freezer.`],
    heartWound: [`That one landed on something soft under the loneliness I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and warmer than corporate.`],
    run: [`Flee Cold Storage? I invented chase between shifts.`, `Break contact? Forever doesn't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and a pulse.`, `You ran twice. The badge logged it. Chase is overtime.`],
    chase: [`You ran twice. Chase is how associates collect company.`, `Second flee. I'm billing cardio in cold.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in forever.`, `Second chase. Prey with a fitness plan and no warmth left.`],
    close: [`Back in your face. Miss the cold?`, `Range ends. Soft hands resume. Freezer hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still walking.`, `Smoke fades. Soft hands resume. Miss the shift?`],
    victory: [`Associate down. Keep the badge. Don't keep the smug.`, `You won. Don't ghost my ghost — the freezer remembers.`],
    victoryHealed: [`You juiced and still took forever. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Cold Storage. Optimistic pulse with a receipt.`],
    victoryKited: [`You kited Eternal Associate. Forever undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime in cold.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the nametag.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Pulse down. Shift updated. Badge still mine — company pending.`, `Verified snack. Freezer solved. Your bag was mid.`],
    defeatCrit: [`You crit forever and still died. Talent without overtime.`, `Crit energy, snack ending. Classic cold romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Nametags write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Stay for the dark walk next time.`],
  },
};
