/** @type {Record<string, any>} */
export const BATCH2 = {
  'amber-silk': {
    open: [
      [`Loss Prevention. Solo. I hang the sale signs — you hang in them.`, `Shrinkage is a love language and I speak it with eight limbs and a headset that never mutes.`],
      [`Dangerous. Decisive. Worth the silk. Not a coupon clipper — prove it.`, `Receipt required. Screaming optional. Silk preferred. Stay pretty while I wrap.`],
      [`Clearance aisle. Soft launch denied. Hold the pose.`, `Everybody shops. Only I get to arrange the display. Tag applied before you arrived.`],
      [`Someone who looks good struggling in the sale signs — that's the lookingFor. Hi.`, `Sweet of you to thrash without being asked. The mirror likes the view. So does channel three.`],
    ],
    hit: [
      [`You scratched the display. Rude. Still wrapping.`, `That one had feelings. Merchandising resentments pending.`],
      [`LP took a nick. Headset crackles. Tag still holds.`, `Ow. The robe remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking silk. Keep shopping — inventory updates live.`, `Bloodied Lead. Still prettier than your form.`],
    ],
    miss: [
      [`Missed the silk. Shrinkage continues.`, `Air through the web. Try again with intent — or a coupon.`],
      [`You swung at Loss Prevention and hit policy. Policy bites back slower.`, `Miss logged. Display unchanged.`],
    ],
    crit: [
      [`That one tore the robe. Emotionally. And also actually.`, `Crit on LP? Someone in Corporate just flinched in a mirror.`],
      [`Okay. Soft spot under the headset. Dangerous shopping.`, `You found the vanity under the silk. Keep going — channel three is listening.`],
    ],
    kits: {
      poison: [`Green sheen. You cooked a marinade for a spider who wraps dinner first.`, `Toxin on silk-adjacent dates. Cute. My blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Floor blooms. Silk burns differently — I invoice differently.`, `Arson mid-aisle. Hot. Illegal. Intimate. Still wrapping.`],
      caltrops: [`Iron teeth. Ankles on the menu. I walk webs for a living.`, `You seeded the aisle with spite. We merchandise around it.`],
      'acid-vial': [`Acid kisses chrome. Your face is the real spill under fluorescent honesty.`, `Chemistry thrown like a drink in Loss Prevention. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in a clearance aisle smells like panic and bleach.`, `Church water on silk. The dead hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your soap through the haze.`, `You hid mid-wrap. Silk finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws on my floor. You trapped Loss Prevention. Irony is a SKU.`, `Bear-trap for aisle prey. I invented commitment issues with teeth.`],
      net: [`Mesh on silk. Commitment layered on commitment. Flail is the receipt.`, `You bagged the wrapper. Bold. The headset is laughing.`],
      'healing-potion': [`Red sip. Juice box for shoppers who plan to live. I prefer you rare and tagged.`, `Healing mid-aisle. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders on every hit. Silk invoices ghosts differently.`, `Salad-dressing warfare in Clearance. Slippery career move.`],
    },
    kitGeneric: [`You opened the bag mid-aisle. That's a write-up in silk.`, `Props. Theater kid. Loss Prevention grades performances.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Headset logged it.`, `Flee, then kit. Shrinkage grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my silk.`, `Runner with a finishing move. Impressed. Offended. Still wrapping.`],
    mHit: [`Tag applied. Don't look surprised — you matched first.`, `That's for the unread coupons and the thrashing you promised.`],
    mHitBloodied: [`Bloodied and still landing. Silk talks.`, `I'm hurt. You're hurt more. Fair trade in Clearance.`],
    mMiss: [`Missed. Don't get cocky — silk is still circling.`, `Lucky. Luck expires when LP gets bored.`],
    winded: [`First scratch on the display. Don't get attached.`, `That tickled. Upgrade your intent or hold the pose.`],
    bruised: [`Color coming in under silk. Keep painting.`, `Mid-date damage. Persistent — like a bad return.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Wrap continues.`, `Bloodied Lead. Finish it or become décor.`],
    heartWound: [`That one landed on something soft under the headset I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and photogenic.`],
    run: [`Flee the aisle? I invented web cardio.`, `Break contact? Shrinkage doesn't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no receipt.`, `You ran twice. Headset logged it. Chase is merchandising.`],
    chase: [`You ran twice. Chase is how LP files grievances.`, `Second flee. I'm billing silk cardio.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in thread.`, `Second chase. Prey with a fitness plan and no coupon left.`],
    close: [`Back in your face. Miss the wrap?`, `Range ends. Soft hands resume. Silk hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still here.`, `Smoke fades. Soft hands resume. Miss the silk?`],
    victory: [`Lead down. Keep the robe. Don't keep the smug.`, `You won. Don't ghost my ghost — inventory remembers.`],
    victoryHealed: [`You juiced and still wrapped the win. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Clearance. Optimistic shopper with a receipt.`],
    victoryKited: [`You kited Loss Prevention. Web wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime in silk.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the wrap.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Shopper down. Inventory updated. Robe's still yours — receipt pending.`, `Verified snack. Shrinkage solved. Your bag was mid.`],
    defeatCrit: [`You crit the Lead and still died. Talent without style.`, `Crit energy, snack ending. Classic aisle romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Clearance writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Hold the pose next time.`],
  },

  grin: {
    open: [
      [`Puddle. Chest. Last good idea in a hallway. Claim within 24h or become inventory.`, `The smile's free. The acid isn't. Do Not Claim — unless you mean it.`],
      [`Greedy hands. Loud heartbeats. Bags nobody missed — hi.`, `I look like a puddle. Or a chest. Or your bad decision. Touch carefully.`],
      [`Lost & Found Asset. Manners sticky. Digestion polite.`, `Surprise is a love language. Your face when the floor moves — that's my favorite form.`],
      [`Someone who claims within 24h or becomes inventory. Clock's ticking. Smile's waiting.`, `Shocking honesty: I inventorizes hunters. You're already on the tag.`],
    ],
    hit: [
      [`You scratched the puddle. Rude. Still smiling.`, `That one had feelings. Acid resentments pending.`],
      [`Asset took a nick. Tag still lies nicely.`, `Ow. The grin remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking acid. Keep claiming — inventory updates live.`, `Bloodied grin. Still sticky. Still polite.`],
    ],
    miss: [
      [`Missed the puddle. Classic kick-first error.`, `Air through the smile. Try again with intent — or a claim form.`],
      [`You swung at Lost & Found and hit manners. Manners bite back slower.`, `Miss logged. Floor unchanged.`],
    ],
    crit: [
      [`That one tore the smile. Emotionally. And also actually.`, `Crit on an asset? Someone in Vault Annex just flinched in a form.`],
      [`Okay. Soft spot under the puddle. Dangerous claiming.`, `You found the acid under the manners. Keep going — I'm digesting the thought.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a puddle that digests first.`, `Toxin on sticky dates. Cute. My acid quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Floor blooms. Fire hates puddles — I hate fire more.`, `Arson mid-claim. Hot. Illegal. Intimate. Still smiling.`],
      caltrops: [`Iron teeth. Ankles on the menu. I am the floor.`, `You seeded spite. Puddles walk it by being walked on.`],
      'acid-vial': [`Acid on acid. Your face is the real spill under hallway honesty.`, `Chemistry thrown like a drink on inventory. Sticky. Personal. Redundant.`],
      'holy-water': [`Blessed tap. Faith on a puddle smells like panic and bleach.`, `Church water on a grin. The dead hate the brand. I just hate the dilution.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your greed through the haze.`, `You hid mid-claim. Puddles find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a mimic. Irony is a SKU labeled Do Not Claim.`, `Bear-trap for hallway prey. I invented commitment issues with lids.`],
      net: [`Mesh on a puddle. Commitment layered on stickiness. Flail is the form.`, `You bagged the asset. Bold. The tag is laughing.`],
      'healing-potion': [`Red sip. Juice for claimers who plan to live. I prefer you rare and inventoried.`, `Healing mid-hallway. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil on a puddle. Greasy riders. Manners slip for no one.`, `Slippery warfare in Vault Annex. Career move for abandoned property.`],
    },
    kitGeneric: [`You opened the bag mid-claim. That's a write-up in acid.`, `Props. Theater kid. Lost & Found grades performances sticky.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Smile still wide.`, `Flee, then kit. Inventory grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my smile.`, `Runner with a finishing move. Impressed. Offended. Still sticky.`],
    mHit: [`Claim applied. Don't look surprised — you matched first.`, `That's for the unread forms and the kick you promised.`],
    mHitBloodied: [`Bloodied and still landing. Manners talk.`, `I'm hurt. You're hurt more. Fair trade in acid.`],
    mMiss: [`Missed. Don't get cocky — the puddle is still circling.`, `Lucky. Luck expires when grins get bored.`],
    winded: [`First scratch on the smile. Don't get attached.`, `That tickled. Upgrade your intent or claim properly.`],
    bruised: [`Color coming in under stickiness. Keep painting.`, `Mid-claim damage. Persistent — like a bad form.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Digestion continues.`, `Bloodied asset. Finish it or become décor on the tag.`],
    heartWound: [`That one landed on something soft under the grin I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and digestible.`],
    run: [`Flee the hallway? I invented chase as a puddle.`, `Break contact? Claims don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no claim form.`, `You ran twice. The tag logged it. Chase is inventory.`],
    chase: [`You ran twice. Chase is how assets collect greed.`, `Second flee. I'm billing cardio in acid.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed sticky.`, `Second chase. Prey with a fitness plan and no manners left.`],
    close: [`Back in your face. Miss the smile?`, `Range ends. Soft acid resumes. Puddle hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still grinning.`, `Smoke fades. Soft acid resumes. Miss the claim?`],
    victory: [`Asset down. Keep the smile. Don't keep the smug.`, `You won. Don't ghost my ghost — inventory remembers.`],
    victoryHealed: [`You juiced and still claimed the win. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Vault Annex. Optimistic claimer with a receipt.`],
    victoryKited: [`You kited a puddle. Sticky wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime in acid.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the grin.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Claimer down. Inventory updated. Smile's still mine — form pending.`, `Verified snack. Lost & Found solved. Your bag was mid.`],
    defeatCrit: [`You crit the asset and still died. Talent without a claim.`, `Crit energy, snack ending. Classic hallway romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. The puddle writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Claim next time.`],
  },

  drool: {
    open: [
      [`Pocket-sized. Adorable. Will trade your afterlife for crisps and call it win-win.`, `Initial here. Initial again. Smile. Cute is the fine print.`],
      [`A pact. A snack. A witness. Someone who skips to the signature — that's you, right?`, `Terms & conditions bite back. You didn't read. Classic. Fetid cloud complimentary.`],
      [`Bad ideas. Contracts in type you can't read. Complimentary regret.`, `Chaos. Sugar. Your worst impulse. Unsigned NDAs left on the table — delicious.`],
      [`Shocking honesty: I sell souls with snack-aisle charm. Initial. Oh — that was a claw.`, `Lawyers turn me off. People who read the terms turn me off. You look like neither. Perfect.`],
    ],
    hit: [
      [`You scratched the cutie. Rude mid-pact.`, `That one had feelings. Contract resentments pending.`],
      [`Associate took a nick. Fine print still holds.`, `Ow. The smile remembers. So do the clauses.`],
    ],
    hitBloodied: [
      [`I'm leaking cute. Keep initialing — pact updates live.`, `Bloodied devil. Still adorable. Still binding.`],
    ],
    miss: [
      [`Missed the snack. Pact continues.`, `Air through the fine print. Try again with intent — or a pen.`],
      [`You swung at Pact & Snacks and hit a clause. Clauses bite slower.`, `Miss logged. Contract unchanged.`],
    ],
    crit: [
      [`That one tore the charm. Emotionally. And also actually.`, `Crit on a pocket fiend? Someone in Legal just flinched on an NDA.`],
      [`Okay. Soft spot under the sugar. Dangerous signing.`, `You found the cloud under the cute. Keep going — I'm listening between initials.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a fiend who sells poison as a perk.`, `Toxin on snack-adjacent dates. Cute. My blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Booth blooms. Fire voids the warranty on cute.`, `Arson mid-pact. Hot. Illegal. Intimate. Still smiling.`],
      caltrops: [`Iron teeth. Ankles on the menu. I fit in pockets.`, `You seeded spite. Contracts walk it anyway.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under booth honesty.`, `Chemistry thrown like a drink on a signature. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a fiend smells like panic and bleach — and my turn-off list.`, `Church water on cute. Holy symbols? Hard no. Wet? Also no.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your impulse through the haze.`, `You hid mid-signature. Fine print finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a contract. Irony is a clause.`, `Bear-trap for booth prey. I invented commitment issues with initials.`],
      net: [`Mesh on a pocket devil. Commitment layered on cute. Flail is the witness.`, `You bagged the associate. Bold. The NDA is laughing.`],
      'healing-potion': [`Red sip. Juice for signers who plan to live. I prefer you rare and bound.`, `Healing mid-pact. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Fine print slips for no one.`, `Slippery warfare in the back booth. Career move for a soul.`],
    },
    kitGeneric: [`You opened the bag mid-pact. That's a write-up in cute.`, `Props. Theater kid. Pact & Snacks grades performances.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Clause still loud.`, `Flee, then kit. Fine print grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my smile.`, `Runner with a finishing move. Impressed. Offended. Still binding.`],
    mHit: [`Clause applied. Don't look surprised — you matched first.`, `That's for the unread terms and the snack you promised.`],
    mHitBloodied: [`Bloodied and still landing. Cute talks.`, `I'm hurt. You're hurt more. Fair trade in crisps.`],
    mMiss: [`Missed. Don't get cocky — the cloud is still circling.`, `Lucky. Luck expires when fiends get bored.`],
    winded: [`First scratch on the charm. Don't get attached.`, `That tickled. Upgrade your intent or initial properly.`],
    bruised: [`Color coming in under sugar. Keep painting.`, `Mid-pact damage. Persistent — like a bad clause.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Pact continues.`, `Bloodied associate. Finish it or become décor in the fine print.`],
    heartWound: [`That one landed on something soft under the cute I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and win-win.`],
    run: [`Flee the booth? I invented chase in snack aisles.`, `Break contact? Pacts don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no witness.`, `You ran twice. The NDA logged it. Chase is contract enforcement.`],
    chase: [`You ran twice. Chase is how associates collect souls.`, `Second flee. I'm billing cardio in regret.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in sugar.`, `Second chase. Prey with a fitness plan and no afterlife left.`],
    close: [`Back in your face. Miss the snack?`, `Range ends. Soft claw resumes. Booth hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still adorable.`, `Smoke fades. Soft claw resumes. Miss the pact?`],
    victory: [`Associate down. Keep the crisps. Don't keep the smug.`, `You won. Don't ghost my ghost — the contract remembers.`],
    victoryHealed: [`You juiced and still signed the win. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in the booth. Optimistic signer with a receipt.`],
    victoryKited: [`You kited a pocket fiend. Fine-print wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is a clause I hate.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the snack.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Signer down. Pact updated. Cute's still mine — soul pending.`, `Verified snack. Booth solved. Your bag was mid.`],
    defeatCrit: [`You crit the cutie and still died. Talent without a witness.`, `Crit energy, snack ending. Classic pact romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Fine print writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Initial next time.`],
  },

  rattlewire: {
    open: [
      [`I kept every appointment. Misplaced the meat. Your invite is declined with perfect posture.`, `Clicking is punctuation, not a mood. On time forever.`],
      [`Someone who doesn't flinch at joints. No late cancels. A heart that keeps the invite — that's the lookingFor.`, `Flesh was a distraction. Punctuality isn't. Be décor or be on schedule.`],
      [`Shortsword. Shortbow. Excellent posture. Calendar holds that outlive flesh.`, `I don't ghost. I reschedule into violence. Your femur has an appointment.`],
      [`Order. Quiet halls. Well-strung bows. Meetings that end when they should.`, `Shocking honesty: "who were you" is a turn-off. Who I am is the calendar.`],
    ],
    hit: [
      [`You scratched the schedule. Rude mid-slot.`, `That one had feelings. Calendar resentments pending.`],
      [`Skeleton took a nick. Posture still holds.`, `Ow. The bones remember. So does the invite.`],
    ],
    hitBloodied: [
      [`I'm leaking marrow-adjacent. Keep the invite — schedule updates live.`, `Bloodied and still punctual. That's not tenure. That's punctuation.`],
    ],
    miss: [
      [`Missed the bones. Schedule continues.`, `Air through quiet halls. Try again with intent — or an RSVP.`],
      [`You swung at Scheduling and hit a hold. Holds bite back on time.`, `Miss logged. Calendar unchanged.`],
    ],
    crit: [
      [`That one tore the posture. Emotionally. And also actually.`, `Crit on a skeleton who kept every appointment? Someone upstairs just twitched on the hour.`],
      [`Okay. Soft spot under the clicks. Dangerous scheduling.`, `You found the quiet under the bones. Keep going — I'm listening between meetings.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned bones that quit chemistry with the meat.`, `Toxin on calendar-adjacent dates. Cute. Punctuality doesn't care.`],
      'alchemists-fire': [`Flask hits. Annex blooms. Fire hates schedules — I hate fire more.`, `Arson mid-slot. Hot. Illegal. Intimate. Still on time.`],
      caltrops: [`Iron teeth. Ankles on the menu. I walk quiet halls.`, `You seeded spite. Bones walk it on schedule.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under ossuary honesty.`, `Chemistry thrown like a drink on an invite. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on bones smells like panic and bleach — and Turn Undead energy.`, `Church water on a calendar. The living hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your lateness through the haze.`, `You hid mid-slot. Bones find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped punctuality. Irony is a late fee.`, `Bear-trap for annex prey. I invented commitment issues with holds.`],
      net: [`Mesh on bones. Commitment layered on posture. Flail is the no-show.`, `You bagged the scheduler. Bold. The calendar is laughing in clicks.`],
      'healing-potion': [`Red sip. Juice for guests who plan to live. I prefer you rare and on time.`, `Healing mid-slot. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Posture slips for no one.`, `Slippery warfare in Ossuary Annex. Career move for a no-show.`],
    },
    kitGeneric: [`You opened the bag mid-slot. That's a write-up in clicks.`, `Props. Theater kid. Scheduling grades performances on the minute.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Late.`, `Flee, then kit. Calendars grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my posture.`, `Runner with a finishing move. Impressed. Offended. Still punctual.`],
    mHit: [`Slot applied. Don't look surprised — you matched first.`, `That's for the unread invites and the flinch you promised.`],
    mHitBloodied: [`Bloodied and still landing. Punctuality talks.`, `I'm hurt. You're hurt more. Fair trade on the hour.`],
    mMiss: [`Missed. Don't get cocky — the clicks are still circling.`, `Lucky. Luck expires when bones get bored.`],
    winded: [`First scratch on the posture. Don't get attached.`, `That tickled. Upgrade your intent or RSVP properly.`],
    bruised: [`Color coming in under bone. Keep painting.`, `Mid-slot damage. Persistent — like a bad cancel.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Schedule continues.`, `Bloodied skeleton. Finish it or become décor in the annex.`],
    heartWound: [`That one landed on something soft under the calendar I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and off-schedule.`],
    run: [`Flee the annex? I invented chase between meetings.`, `Break contact? Calendars don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and a late cancel.`, `You ran twice. The hold logged it. Chase is punctuation.`],
    chase: [`You ran twice. Chase is how skeletons collect no-shows.`, `Second flee. I'm billing cardio in clicks.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed on time.`, `Second chase. Prey with a fitness plan and no invite left.`],
    close: [`Back in your face. Miss the clicks?`, `Range ends. Soft blade resumes. Annex hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still punctual.`, `Smoke fades. Soft blade resumes. Miss the slot?`],
    victory: [`Skeleton down. Keep the posture. Don't keep the smug.`, `You won. Don't ghost my ghost — the calendar remembers.`],
    victoryHealed: [`You juiced and still took the slot. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in the annex. Optimistic guest with a receipt.`],
    victoryKited: [`You kited a scheduler. Punctuality undone by jogging.`, `Ran me ragged then finished it. Cardio is a late fee.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the clicks.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Guest down. Schedule updated. Posture's still mine — invite pending.`, `Verified snack. Annex solved. Your bag was mid.`],
    defeatCrit: [`You crit the bones and still died. Talent without an RSVP.`, `Crit energy, snack ending. Classic calendar romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Clicks write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Be on time next time.`],
  },

  'neon-howl': {
    open: [
      [`Three bodies. One hunger. Neon on wet concrete like war paint.`, `We don't "synergize" — we braid into one chase. Run. We prefer the sound.`],
      [`Prey that runs. Prey that bites back. Anything that makes the howl honest.`, `Pack tactics. Pink streaks. A howl you'll hear twice. No mercy script.`],
      [`Underpass Pack. Chase Division. Wet neon. Look wrong.`, `Lone wolves spoil the meat. "I work better alone" is a turn-off and a menu item.`],
      [`Shocking honesty: we are three hearts braided into one chase. Hit rates written in paws.`, `Sweet of you to thrash without being asked. Keep thrashing. The underpass likes the soundtrack.`],
    ],
    hit: [
      [`You scratched the braid. Rude mid-hunt.`, `That one had feelings. Pack resentments pending.`],
      [`Pack took a nick. Howl still holds.`, `Ow. The neon remembers. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep running — hunt updates live.`, `Bloodied pack. Still braided. Still hungry.`],
    ],
    miss: [
      [`Missed the pack. Chase continues.`, `Air through wet neon. Try again with intent — or run properly.`],
      [`You swung at Chase Division and hit a howl. Howls bite back louder.`, `Miss logged. Braid unchanged.`],
    ],
    crit: [
      [`That one tore the braid. Emotionally. And also actually.`, `Crit on the pack? Someone on the underpass just flinched in pink.`],
      [`Okay. Soft spot under the neon. Dangerous hunting.`, `You found the hunger under the howl. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a pack that drinks first.`, `Toxin on chase-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Underpass blooms. Fire hates wet neon — we hate fire more.`, `Arson mid-hunt. Hot. Illegal. Intimate. Still braided.`],
      caltrops: [`Iron teeth. Ankles on the menu. We run for a living.`, `You seeded spite. Packs walk it in paws.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under neon honesty.`, `Chemistry thrown like a drink on a chase. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on wet concrete smells like panic and bleach.`, `Church water on a pack. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your fear through the haze.`, `You hid mid-hunt. Packs find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a chase. Irony is a howl.`, `Bear-trap for underpass prey. We invented commitment issues with flanks.`],
      net: [`Mesh on a pack. Commitment layered on braid. Flail is the soundtrack.`, `You bagged the hunt. Bold. The howl is laughing.`],
      'healing-potion': [`Red sip. Juice for prey who plan to live. We prefer you rare and running.`, `Healing mid-chase. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Neon slips for no one.`, `Slippery warfare under the underpass. Career move for lunch.`],
    },
    kitGeneric: [`You opened the bag mid-hunt. That's a write-up in howls.`, `Props. Theater kid. Chase Division grades performances in paws.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Perfect prey.`, `Flee, then kit. Packs grade that soft — and chase it.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our braid.`, `Runner with a finishing move. Impressed. Offended. Still hungry.`],
    mHit: [`Flank applied. Don't look surprised — you matched first.`, `That's for the unread howl and the run you promised.`],
    mHitBloodied: [`Bloodied and still landing. Pack talks.`, `We're hurt. You're hurt more. Fair trade in neon.`],
    mMiss: [`Missed. Don't get cocky — the braid is still circling.`, `Lucky. Luck expires when packs get bored.`],
    winded: [`First scratch on the braid. Don't get attached.`, `That tickled. Upgrade your intent or run properly.`],
    bruised: [`Color coming in under neon. Keep painting.`, `Mid-hunt damage. Persistent — like a bad lone wolf.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Chase continues.`, `Bloodied pack. Finish it or become décor on wet concrete.`],
    heartWound: [`That one landed on something soft under the howl we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and honest.`],
    run: [`Flee the underpass? We invented chase. We prefer the sound.`, `Break contact? Hunts don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs — our favorite.`, `You ran twice. The braid logged it. Chase is love.`],
    chase: [`You ran twice. Chase is how packs collect honesty.`, `Second flee. We're billing cardio in howls.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in neon.`, `Second chase. Prey with a fitness plan and no alone left.`],
    close: [`Back in your face. Miss the howl?`, `Range ends. Soft teeth resume. Pack hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still braided.`, `Smoke fades. Soft teeth resume. Miss the hunt?`],
    victory: [`Pack down. Keep the neon. Don't keep the smug.`, `You won. Don't ghost our ghost — the howl remembers.`],
    victoryHealed: [`You juiced and still took the hunt. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory under neon. Optimistic prey with a receipt.`],
    victoryKited: [`You kited Chase Division. Pack wisdom undone by jogging — ironically our sport.`, `Ran us ragged then finished it. Cardio is a war crime we also commit.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the braid.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Prey down. Hunt updated. Howl's still ours — blood pending.`, `Verified snack. Underpass solved. Your bag was mid.`],
    defeatCrit: [`You crit the pack and still died. Talent without a chase.`, `Crit energy, snack ending. Classic neon romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan — almost our love language.`, `Fleeing into a snack ending. Howls write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Run next time.`],
  },
};
