/** @type {Record<string, import('./_schema.mjs').VoiceBank>} */
export const BATCH1 = {
  patches: {
    open: [
      [`Shinies first. I've outlived three nametags waiting for someone this sparkly.`, `Soft secret: I bill what I love. Hard truth: I loved you the second you cast a reflection.`],
      [`Three centuries unpaid. Still no welcome. You walked in shining like a shelf I forgot to claim.`, `They say Loss Prevention invented me. Conspiracy? I invented the alcove — and I sleep under it.`],
      [`Don't flinch. The ledger is watching. So am I.`, `Cute pulse. Still paying in scrap. Half a sandwich says you flinch first.`],
      [`Hands that know the price — or hands that steal. I remember the SKU either way.`, `I've scavenged worse dates. You're almost interesting. Leave the pretty metal where I can see it.`],
    ],
    hit: [
      [`That cut stays. I file claims. Including this one.`, `Ow. Emotionally. And also the blood part. Still billing.`],
      [`You tagged the temp under the shelf they forgot. Bold.`, `Noted in my private ledger. Next swing costs shinies.`],
    ],
    hitBloodied: [
      [`I'm leaking shinies of my own. Keep going — I'm listening.`, `Bloodied and still filing. Three centuries of memory don't quit for a nick.`],
    ],
    miss: [
      [`Air. Tall-people error. The alcove dodges for me.`, `You talk theft better than you land it. Swing at the dumpster.`],
      [`Missed the scavenger. Classic. I keep what falls — including your aim.`, `Try again with intent. Or leave glitter and walk.`],
    ],
    crit: [
      [`That one hurt. Claws under three hundred years of scrap.`, `Crit on a temp? Someone who never welcomed me just twitched across centuries.`],
      [`Okay. That was almost a shiny. Soft spot found. Keep digging.`, `You found the alcove under the armor. Dangerous shopping.`],
    ],
    kits: {
      poison: [`Green sheen on the edge. Dinner for a corpse dead on paper forever.`, `Toxin coat. My blood quit years ago — yours still believes in chemistry.`],
      'alchemists-fire': [`Flask hits. Floor blooms orange. My shinies hate heat.`, `Arson in the alcove. Sparks are the only honest thing you brought.`],
      caltrops: [`Iron teeth across the tile. Ankles on the menu — I've eaten worse floors.`, `You seeded spite. I walk dumpsters for a living.`],
      'acid-vial': [`Vial arcs. Fizz on chrome. Your face is the real spill.`, `Acid kisses scrap. As-is. No returns on personality.`],
      'holy-water': [`Blessed tap in a flask. Faith smells like chlorine in a place God forgot.`, `You brought church into a dumpster fight. Bold. Sticky. Still mine.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your soap under the haze.`, `You hid mid-date. The alcove invented hide-and-seek with teeth.`],
      'hunting-trap': [`Iron jaws. You set a trap on a scavenger. Irony noted. Teeth noted.`, `Bear-trap for alcove prey. Breakroom had worse furniture.`],
      net: [`Mesh kisses shoulders. Commitment issues with holes.`, `You bagged the temp like a return. Flail is the receipt I keep.`],
      'healing-potion': [`Red sip. Juice for people who plan to live. Optimistic. I prefer you rare.`, `Healing mid-fight. Soft prey topping off. Delicious. Still billed.`],
      'oil-flask': [`Oil sheets the blade. Every hit a greasy rider on my scrap.`, `Slippery warfare. My shinies will never forgive you.`],
    },
    kitGeneric: [`Props from the bag. Theater kid with a death wish and no price tag.`, `You opened the kit like a love letter. I'm answering in scrap.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Alcove grades that soft.`, `Flee, then kit. I remember the SKU of every runner.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my shinies.`, `Runner with a finishing move. Impressed. Offended. Filing both.`],
    mHit: [`Don't look surprised — you matched first. That's for the unread centuries.`, `Landed. For every hand that borrowed without asking the price.`],
    mHitBloodied: [`Leaking and still landing. Memory talks louder than blood.`, `I'm hurt. You're hurt more. Fair trade under the forgotten shelf.`],
    mMiss: [`Missed. Don't get cocky — I'm still circling the shinies.`, `Lucky. Luck expires when scavengers get bored.`],
    winded: [`First scratch. Don't get attached to the feeling.`, `That tickled. Upgrade your intent or leave the glitter.`],
    bruised: [`Color coming in. Keep painting the temp.`, `Mid-date damage. Persistent — like a bad borrow.`],
    bloodied: [`I'm leaking. You're still soft. Fix one of those.`, `Bloodied and still standing. Finish it or become décor in the alcove.`],
    heartWound: [`That one landed on something soft I wasn't advertising under the shelf.`, `Don't look at me like that while you're winning. It's rude and effective.`],
    run: [`You fled the alcove? I invented dumpster cardio centuries ago.`, `Break contact? Violence doesn't do rain checks where I sleep.`],
    runAgain: [`Second escape. Prey with legs and no dignity.`, `You ran twice. The ledger noticed. Chase is how temps file grievances.`],
    chase: [`You ran twice. Chase is how I bill cardio.`, `Second flee. Shinies don't wait for cowards.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in scrap.`, `Second chase. Prey with a fitness plan and no price sense.`],
    close: [`Back in your face. Miss the shinies?`, `Range ends. Soft hands resume. Alcove hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still here. Still billing.`, `Smoke fades. Soft hands resume. Miss the alcove?`],
    victory: [`Temp status: terminated. Take the shinies. Leave the attitude.`, `You won. Don't ghost my ghost — I've waited longer than your bloodline.`],
    victoryHealed: [`You juiced up and still won. Soft. Effective. I almost respect the cowardice.`, `Healing potion victory. Optimistic prey with a receipt I can't bill.`],
    victoryKited: [`You kited a scavenger. Three centuries of dumpster wisdom, undone by jogging.`, `Ran me ragged then finished it. Cardio is a war crime and you committed it.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about my shinies.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Verified snack. Shrinkage solved. Your bag was mid.`, `Down you go. I've outlived prettier corpses under worse shelves.`],
    defeatCrit: [`You crit hard and still died. Talent without a welcome.`, `Crit energy, snack ending. Classic alcove romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. I file that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Still unpaid.`],
  },

  'dumpster-king': {
    open: [
      [`This dumpster has heraldry. You have a badge and the manners of a delivery driver.`, `Kneel. Tip tribute into the lid. Or leave lighter. The smell is the crown — bow to it.`],
      [`Usurpers always arrive with soap. Cute. The kingdom is stink and I am the constitution.`, `Three audits drowned here. The smell stayed. So did I. Sweet of you to kneel without being asked.`],
      [`Rivals worth the claws — or peasants with badges. Pick a lane.`, `Leftovers fit for a king. You smell like neither. Prove me wrong.`],
      [`A heart that bows to the smell — or dies trying to rebrand it. Which are you?`, `Shocking honesty: this throne outlived floods. You will not outlive me.`],
    ],
    hit: [
      [`You scratched the crown. Usurper manners.`, `That one had teeth. I resent the familiarity.`],
      [`Blood on heraldry. Noted. Tribute still due.`, `Ow. The kingdom flinches for no one — except that.`],
    ],
    hitBloodied: [
      [`I bleed. The smell does not. Kneel harder.`, `Bloodied sovereign. Still crowned. Still stinking of law.`],
    ],
    miss: [
      [`Missed the throne. Classic peasant aim.`, `Air. Expensive for a usurper. Swing like you mean the lid.`],
      [`You swung at royalty and hit refuse. Same difference to you, apparently.`, `Miss logged. Crown unchanged.`],
    ],
    crit: [
      [`That one tore the heraldry. Emotionally. And also actually.`, `Crit on a king? The dumpster remembers. So do my claws.`],
      [`Okay. Soft spot under the crown. Dangerous tribute.`, `You found flesh under the smell. Keep going — I'm listening in silence.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned the king's dinner. Rude. Effective.`, `Toxin for a sovereign. Cute. My blood is older than your soap.`],
      'alchemists-fire': [`Flask hits. Throne blooms. Fire is trash day's cousin — I hate both.`, `Arson on my kingdom. Hot. Illegal. Still kneeling recommended.`],
      caltrops: [`Iron teeth. Ankles on the menu. I walk grit for a living.`, `You seeded spite under my lid. I walk it crowned.`],
      'acid-vial': [`Acid kiss on heraldry. Your face is the real spill.`, `Chemistry thrown like a peasant tantrum. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in a dumpster smells like panic and bleach.`, `Church water on the crown. Gods hate the smell. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your fear under soap.`, `You hid mid-tribute. The throne finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws on my floor. You trapped a king. Irony is a kind of tribute.`, `Bear-trap for throne prey. I invented commitment with claws.`],
      net: [`Mesh on royalty. Commitment layered on heraldry. Flail is the tribute.`, `You bagged the crown. Bold. The smell is laughing.`],
      'healing-potion': [`Red sip. Juice for usurpers who plan to live. I prefer you rare and kneeling.`, `Healing mid-throne. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders on every claw. The kingdom slips for no one.`, `Slippery warfare in Maztek Rear. Career move for a corpse.`],
    },
    kitGeneric: [`Props from the bag. Peasant theater. The crown grades performances.`, `You opened the kit like an offering. I'm answering in teeth.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Kings notice.`, `Flee, then kit. Tribute grades that soft.`],
    hcritRan: [`You fled then crit. Soft peasant into a hard landing.`, `Runner with a finishing move. Impressed. Offended. Still crowned.`],
    mHit: [`Don't look surprised — you matched first. That's for the unread tribute.`, `Landed. For every usurper who said synergy near my lid.`],
    mHitBloodied: [`Bloodied and still landing. Crowns talk.`, `I'm hurt. You're hurt more. Fair trade in the kingdom of stink.`],
    mMiss: [`Missed. Don't get cocky — the smell is still circling.`, `Lucky. Luck expires when kings get bored.`],
    winded: [`First scratch on the crown. Don't get attached.`, `That tickled. Upgrade your intent or kneel properly.`],
    bruised: [`Color coming in under heraldry. Keep painting.`, `Mid-tribute damage. Persistent — like a bad delivery.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Crown continues.`, `Bloodied king. Finish it or become décor in the lid.`],
    heartWound: [`That one landed on something soft under the smell I wasn't advertising.`, `Don't look at me like that while you're winning. It's rude and almost respectful.`],
    run: [`Flee the throne? I invented chase in alleys.`, `Break contact? Kingdoms don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no tribute.`, `You ran twice. The crown logged it. Chase is heraldry.`],
    chase: [`You ran twice. Chase is how kings collect.`, `Second flee. I'm billing cardio in leftover grease.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in stink.`, `Second chase. Prey with a fitness plan and no manners.`],
    close: [`Back in your face. Miss the smell?`, `Range ends. Soft claws resume. Throne hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still crowned.`, `Smoke fades. Soft claws resume. Miss the kingdom?`],
    victory: [`King down. Keep the crown if you can lift it. Leave the smug.`, `You won. Don't ghost my ghost — the smell remembers.`],
    victoryHealed: [`You juiced and still took the throne. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Maztek Rear. Optimistic usurper with a receipt.`],
    victoryKited: [`You kited a king. Throne wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is treason.`],
    victoryCrit: [`You crit your way to the crown. Claws and closure.`, `Crit path victory. Ugly. Clean. Bow anyway.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending for a king.`],
    defeat: [`Peasant down. Inventory updated. Crown's still mine — tribute pending.`, `Verified snack. Kingdom solved. Your bag was mid.`],
    defeatCrit: [`You crit the king and still died. Talent without tribute.`, `Crit energy, snack ending. Classic alley romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. The dumpster writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Kneel next time.`],
  },

  'bleed-static': {
    open: [
      [`Not needy — calibrated. Your unused PTO tastes like a first date you'll pretend was consensual.`, `Stay still. I'm almost done falling in love with the skip in your pulse.`],
      [`Exposed necks. Warm circuits. People who skip sleep and call it ambition — hi.`, `HR calls it benefits. I call it intimacy with a receipt. Neck out.`],
      [`One sip. Maybe two. Don't swat mid-confession — detach like an adult. After.`, `Shocking honesty: I fell in love with the skip before I learned your name.`],
      [`Tiny drill. Zero personal space. Experience written on the receipt.`, `Humming lights. Open wounds. The skip when the shift starts — that's my love song.`],
    ],
    hit: [
      [`You scratched the needle. Rude mid-date.`, `That one had feelings. I resent the interruption.`],
      [`Benefits took a nick. Pulse still skippable.`, `Ow. Calibrated resentment pending.`],
    ],
    hitBloodied: [
      [`I'm leaking. Keep skipping — I'm still listening to your heart.`, `Bloodied and still attached. That's intimacy, not tenure.`],
    ],
    miss: [
      [`Missed the needle. Ambition continues.`, `Air through the vent. Try again with intent — or hold still.`],
      [`You swung at benefits and hit policy. Policy bites slower. I bite now.`, `Miss logged. Pulse unchanged.`],
    ],
    crit: [
      [`That one tore the romance. Emotionally. And also actually.`, `Crit on a vampire of unused days? Someone's PTO just twitched.`],
      [`Okay. Soft spot under the drill. Dangerous dating.`, `You found the skip under my calibration. Keep going — I'm listening.`],
    ],
    kits: {
      poison: [`Green sheen. You marinated a date who drinks first.`, `Toxin on needle-adjacent romance. Cute. My thirst quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Vent blooms. Heat ruins the drip.`, `Arson mid-sip. Hot. Illegal. Intimate. Still calibrated.`],
      caltrops: [`Iron teeth. Ankles on the menu. I fly for a living.`, `You seeded spite. I land anyway — on necks.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under neon honesty.`, `Chemistry thrown like a drink on a first date. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in an IV lounge smells like panic and bleach.`, `Church water on a benefits vampire. The dead hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your pulse through the haze.`, `You hid mid-sip. Needles find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a clinger. Irony is a love language.`, `Bear-trap for vent prey. I invented commitment issues with drills.`],
      net: [`Mesh — my turn-off, your prop. Commitment with holes.`, `You bagged the needle. Bold. Swatting energy. I noticed.`],
      'healing-potion': [`Red sip. Juice for people who plan to live. I prefer your unused days rare.`, `Healing mid-date. Soft. Optimistic. Delicious PTO.`],
      'oil-flask': [`Oil sheets. Greasy riders. The vent slips for no romance.`, `Slippery warfare mid-sip. Career move for a snack.`],
    },
    kitGeneric: [`You opened the bag mid-date. That's a write-up in intimacy.`, `Props. Theater kid. Benefits grades performances by the skip.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Pulse still loud.`, `Flee, then kit. Calibrated thirst grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my drill.`, `Runner with a finishing move. Impressed. Offended. Still thirsty.`],
    mHit: [`Attached. Don't look surprised — you matched first.`, `That's for the unread PTO and the thrashing you promised.`],
    mHitBloodied: [`Bloodied and still landing. Intimacy talks.`, `I'm hurt. You're hurt more. Fair trade in unused days.`],
    mMiss: [`Missed. Don't get cocky — the skip is still circling.`, `Lucky. Luck expires when benefits get bored.`],
    winded: [`First scratch on the drip. Don't get attached — that's my job.`, `That tickled. Upgrade your intent or hold still.`],
    bruised: [`Color coming in under neon. Keep painting.`, `Mid-date damage. Persistent — like a bad enrollment.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Sip continues.`, `Bloodied vampire. Finish it or become décor in the vent.`],
    heartWound: [`That one landed on something soft I was calibrating carefully.`, `Don't look at me like that while you're winning. It's rude and almost consensual.`],
    run: [`Flee the vent? I invented chase cardio for necks.`, `Break contact? Romance doesn't do rain checks mid-sip.`],
    runAgain: [`Second escape. Prey with legs and no unused days left.`, `You ran twice. The skip logged it. Chase is intimacy.`],
    chase: [`You ran twice. Chase is how I collect PTO.`, `Second flee. I'm billing cardio in heartbeats.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in drips.`, `Second chase. Prey with a fitness plan and no personal space left.`],
    close: [`Back on your neck. Miss the skip?`, `Range ends. Soft drill resumes. Vent hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still thirsty.`, `Smoke fades. Soft drill resumes. Miss the drip?`],
    victory: [`Vampire down. Keep the unused days. Don't keep the smug.`, `You won. Don't ghost my ghost — the skip remembers.`],
    victoryHealed: [`You juiced and still won. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in the vent. Optimistic prey with a receipt.`],
    victoryKited: [`You kited a benefits vampire. Calibration undone by jogging.`, `Ran me ragged then finished it. Cardio is a hard no mid-date.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the sip.`],
    victoryNet: [`You bagged me and finished the job. My turn-off became your ending.`, `Net plus win. Soft bag into a hard detach.`],
    defeat: [`Shopper down — I mean date. Inventory of blood updated.`, `Verified snack. Benefits solved. Your bag was mid.`],
    defeatCrit: [`You crit hard and still died. Talent without unused days.`, `Crit energy, snack ending. Classic vent romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. The skip writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Stay still next time.`],
  },

  knuckle: {
    open: [
      [`Smash good. Talk boring.`, `You look smashable. Escalate.`],
      [`Ticket open. Door looks like you.`, `Talk is hallway. Smash is door.`],
      [`Big axe. Zero plan. Now.`, `Hit back. Briefly.`],
      [`Queue empty soon.`, `Status: you. Soft skill: smash.`],
    ],
    hit: [
      [`Ow.`, `Noted. Smash harder.`],
      [`Hit. Still standing.`, `Feelings? No. Smash.`],
    ],
    hitBloodied: [
      [`Leaking. Still smash.`, `Hurt. You softer.`],
    ],
    miss: [
      [`Miss. Try again.`, `Air. Useless.`],
      [`Swing real.`, `Miss. Door still here.`],
    ],
    crit: [
      [`That hurt. Keep.`, `Crit. Listening with fists.`],
      [`Soft spot. Ugly.`, `Good hit. More.`],
    ],
    kits: {
      poison: [`Green. Coward spice.`, `Poison. Smash anyway.`],
      'alchemists-fire': [`Fire. Hot. Smash.`, `Burn. Still axe.`],
      caltrops: [`Floor teeth. Walk.`, `Spite seeds. Stomp.`],
      'acid-vial': [`Acid. Face spill.`, `Chem. Smash wet.`],
      'holy-water': [`Church wet. Hate.`, `Blessed. Still smash.`],
      smokestick: [`Fog. Smell you.`, `Hide. Find. Smash.`],
      'hunting-trap': [`Trap. Irony. Stomp.`, `Jaws. Break.`],
      net: [`Bag. Flail. Free.`, `Caught. Smash mesh.`],
      'healing-potion': [`Juice. Soft. Rare preferred.`, `Heal. Still snack.`],
      'oil-flask': [`Oil. Slip. Smash.`, `Grease. Ugly.`],
    },
    kitGeneric: [`Bag props. Smash bag.`, `Kit. Answer: axe.`],
    kitRan: [`Ran. Then bag. Soft.`, `Flee. Kit. Smash both.`],
    hcritRan: [`Ran. Crit. Weird.`, `Runner hit hard. Still smash.`],
    mHit: [`Hit. Matched first.`, `Landed. Queue shorter.`],
    mHitBloodied: [`Bleed. Still land.`, `Hurt. You hurt more.`],
    mMiss: [`Miss. Still circling.`, `Lucky. Expires.`],
    winded: [`Scratch. Meh.`, `Tickle. Hit harder.`],
    bruised: [`Color. Keep.`, `Bruise. Paint more.`],
    bloodied: [`Leaking. Soft you.`, `Blood. Finish or décor.`],
    heartWound: [`Soft spot. Rude.`, `Winning look. Hate it. Effective.`],
    run: [`Fled. Chase.`, `Run? No rain check.`],
    runAgain: [`Ran twice. Noticed.`, `Second flee. Chase.`],
    chase: [`Chase. Grievance.`, `Flee. Cardio billed in fists.`],
    chase2: [`Chase twice. Done talking.`, `Second chase. No dignity.`],
    close: [`Close. Miss me?`, `Range end. Hands.`],
    closeSmoke: [`Through fog. Still here.`, `Smoke gone. Smash.`],
    victory: [`Down. Win yours.`, `You won. Ghost later.`],
    victoryHealed: [`Juiced. Won. Soft.`, `Heal win. Coward. Effective.`],
    victoryKited: [`Kited. Jogged. Hate.`, `Ran me. Finished. War crime.`],
    victoryCrit: [`Crit path. Done.`, `Ugly clean win.`],
    victoryNet: [`Bagged. Finished.`, `Net win. Hard end.`],
    defeat: [`Snack. Bay solved.`, `Down. On brand.`],
    defeatCrit: [`Crit. Still dead.`, `Talent. Snack.`],
    defeatRan: [`Ran. Dead. Planless.`, `Flee snack. Classic.`],
    defeatHeal: [`Juiced. Dirt.`, `Heal then die. Soft.`],
  },

  'sister-static': {
    open: [
      [`Snow on a screen that shouldn't still glow. You're live on Channel 7 whether you like it or not.`, `Last song on a dead station — dance until the signal eats the room.`],
      [`Bright souls. Bad reception. Dancers who can't change the channel — welcome.`, `Somewhere a producer still thinks this is a test pattern. Ratings never die here.`],
      [`Glamour is a frequency. You're off-key. Stay anyway.`, `Hold music from before gods had names. Crush for the ratings. Soft launch denied — forever.`],
      [`The hum between stations. Fear as applause. Mandatory listens.`, `Shocking honesty: I broadcast loneliness until it harmonizes. Join the snow.`],
    ],
    hit: [
      [`You scratched the signal. Rude mid-song.`, `That one had feelings. Static resentments pending.`],
      [`Channel took a nick. Headset of the dead crackles.`, `Ow. The snow remembers. So do I.`],
    ],
    hitBloodied: [
      [`I'm leaking light. Keep dancing — ratings update live.`, `Bloodied host. Still prettier than your reception.`],
    ],
    miss: [
      [`Missed the ghost. Snow continues.`, `Air through dead air. Try again with intent — or stay tuned.`],
      [`You swung at Channel 7 and hit a commercial break. Break bites back.`, `Miss logged. Broadcast unchanged.`],
    ],
    crit: [
      [`That one tore the glamour. Emotionally. And also actually.`, `Crit on a dead host? Someone in the afterlife just flinched on air.`],
      [`Okay. Soft spot under the snow. Dangerous listening.`, `You found the frequency under the crush. Keep going — I'm broadcasting.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a broadcast that outlived poison.`, `Toxin on dead-air dates. Cute. My blood quit with the meat.`],
      'alchemists-fire': [`Flask hits. Studio blooms. Fire hates snow — I hate fire more.`, `Arson mid-song. Hot. Illegal. Intimate. Still on air.`],
      caltrops: [`Iron teeth. Ankles on the menu. I float for a living.`, `You seeded spite. Snow walks it anyway.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under ghost light.`, `Chemistry thrown like a drink on a live mic. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on Channel 7 smells like panic and old tubes.`, `Church water on dead glamour. The living hate the brand. I just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. I still smell your spark through the haze.`, `You hid mid-broadcast. Snow finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a signal. Irony is a rerun.`, `Bear-trap for Channel 7 prey. I invented commitment issues with hold music.`],
      net: [`Mesh on a ghost. Commitment layered on snow. Flail is the applause.`, `You bagged the host. Bold. The producer is laughing in hell.`],
      'healing-potion': [`Red sip. Juice for dancers who plan to live. I prefer you rare and tuned in.`, `Healing mid-song. Soft. Optimistic. Delicious ratings.`],
      'oil-flask': [`Oil sheets. Greasy riders. Snow slips for no commercial.`, `Slippery warfare on dead air. Career move for a corpse with spark.`],
    },
    kitGeneric: [`You opened the bag mid-broadcast. That's a write-up in dead ratings.`, `Props. Theater kid. Channel 7 grades performances in snow.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Signal still loud.`, `Flee, then kit. Dead air grades that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on my frequency.`, `Runner with a finishing move. Impressed. Offended. Still live.`],
    mHit: [`Hug applied. Don't look surprised — you matched first.`, `That's for the unread spark and the dance you promised.`],
    mHitBloodied: [`Bloodied and still landing. Ratings talk.`, `I'm hurt. You're hurt more. Fair trade in dead air.`],
    mMiss: [`Missed. Don't get cocky — the snow is still circling.`, `Lucky. Luck expires when Channel 7 gets bored.`],
    winded: [`First scratch on the glow. Don't get attached.`, `That tickled. Upgrade your intent or hold the pose for camera.`],
    bruised: [`Color coming in under snow. Keep painting.`, `Mid-song damage. Persistent — like a bad rerun.`],
    bloodied: [`I'm leaking. You're still soft. Fix one. Broadcast continues.`, `Bloodied host. Finish it or become décor in the test pattern.`],
    heartWound: [`That one landed on something soft I was broadcasting carefully.`, `Don't look at me like that while you're winning. It's rude and great TV.`],
    run: [`Flee Channel 7? I invented chase in static.`, `Break contact? Dead stations don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no reception.`, `You ran twice. The snow logged it. Chase is programming.`],
    chase: [`You ran twice. Chase is how hosts collect spark.`, `Second flee. I'm billing cardio in hums.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in snow.`, `Second chase. Prey with a fitness plan and no channel left.`],
    close: [`Back in your face. Miss the last song?`, `Range ends. Soft hug resumes. Snow hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still glowing.`, `Smoke fades. Soft hug resumes. Miss Channel 7?`],
    victory: [`Host down. Keep the spark. Don't keep the smug.`, `You won. Don't change the channel on my ghost — ratings remember.`],
    victoryHealed: [`You juiced and still won. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory on dead air. Optimistic dancer with a receipt.`],
    victoryKited: [`You kited Channel 7. Broadcast wisdom undone by jogging.`, `Ran me ragged then finished it. Cardio is a commercial break I hate.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the snow.`],
    victoryNet: [`You bagged me and finished the job. Commitment issues resolved on air.`, `Net plus win. Soft bag into a hard sign-off.`],
    defeat: [`Dancer down. Ratings updated. Glow's still mine — spark pending.`, `Verified snack. Channel solved. Your bag was mid.`],
    defeatCrit: [`You crit the host and still died. Talent without reception.`, `Crit energy, snack ending. Classic dead-air romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Snow writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Stay tuned next time.`],
  },
};
