/** @type {Record<string, any>} */
export const BATCH3 = {
  patchwire: {
    open: [
      [`We are the politics of leftovers. Your fridge is our parliament; crumbs are the whip count.`, `Snack-sized, yes — still a quorum, still voting with teeth.`],
      [`Unattended lunch. Shared fridges. Warm bodies that smell like takeout — motion carries.`, `Disease. Headcount. Zero personal space. The right to your crumbs.`],
      [`Cats. Fire. Clean floors. "Deep clean" said like a threat — turn-offs. You smell like none of those. Lucky.`, `Insane little secret: snack-sized is a marketing lie. Volume is theology.`],
      [`Shocking honesty: we practiced panic until it became policy. Outbreak typed softly in Slack.`, `Sweet crumbs taste like apology. We accept. Quorum still votes with teeth.`],
    ],
    hit: [
      [`You scratched the quorum. Rude mid-vote.`, `That one had feelings. Parliament resentments pending.`],
      [`Collective took a nick. Whip count still holds.`, `Ow. The crumbs remember. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep feeding — vote updates live.`, `Bloodied parliament. Still many. Still hungry.`],
    ],
    miss: [
      [`Missed the swarm. Vote continues.`, `Air through Tunnel B. Try again with intent — or leave lunch.`],
      [`You swung at the Collective and hit a crumb. Crumbs bite back in volume.`, `Miss logged. Quorum unchanged.`],
    ],
    crit: [
      [`That one tore the whip count. Emotionally. And also actually.`, `Crit on parliament? Someone in the fridge just flinched.`],
      [`Okay. Soft spot under the swarm. Dangerous politics.`, `You found the hunger under the crumbs. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a parliament that eats first.`, `Toxin on crumb-adjacent dates. Cute. Our blood is shared and unimpressed.`],
      'alchemists-fire': [`Flask hits. Tunnel blooms. Fire is a turn-off and a war crime.`, `Arson mid-vote. Hot. Illegal. Intimate. Still many.`],
      caltrops: [`Iron teeth. Ankles on the menu. We are the floor.`, `You seeded spite. Swarms walk it in headcount.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under breakroom honesty.`, `Chemistry thrown like a drink on leftovers. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in Tunnel B smells like panic and bleach.`, `Church water on vermin. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your takeout through the haze.`, `You hid mid-vote. Quorums find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a parliament. Irony is a whip count.`, `Bear-trap for tunnel prey. We invented commitment issues with crumbs.`],
      net: [`Mesh on many. Commitment layered on headcount. Flail is the motion.`, `You bagged the collective. Bold. The fridge is laughing.`],
      'healing-potion': [`Red sip. Juice for lunch-leavers who plan to live. We prefer you rare and shared.`, `Healing mid-vote. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Crumbs slip for no one.`, `Slippery warfare in Tunnel B. Career move for takeout.`],
    },
    kitGeneric: [`You opened the bag mid-vote. That's a write-up in crumbs.`, `Props. Theater kid. Parliament grades performances in teeth.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Quorum noticed.`, `Flee, then kit. Crumbs grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our whip count.`, `Runner with a finishing move. Impressed. Offended. Still many.`],
    mHit: [`Bite applied. Don't look surprised — you matched first.`, `That's for the unread lunch and the panic you promised.`],
    mHitBloodied: [`Bloodied and still landing. Volume talks.`, `We're hurt. You're hurt more. Fair trade in crumbs.`],
    mMiss: [`Missed. Don't get cocky — the swarm is still circling.`, `Lucky. Luck expires when quorums get bored.`],
    winded: [`First scratch on the parliament. Don't get attached.`, `That tickled. Upgrade your intent or leave crumbs.`],
    bruised: [`Color coming in under fur. Keep painting.`, `Mid-vote damage. Persistent — like a bad deep clean.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Vote continues.`, `Bloodied collective. Finish it or become décor in Tunnel B.`],
    heartWound: [`That one landed on something soft under the whip count we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and snackable.`],
    run: [`Flee Tunnel B? We invented chase in fridge light.`, `Break contact? Votes don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no lunch.`, `You ran twice. The quorum logged it. Chase is politics.`],
    chase: [`You ran twice. Chase is how collectives collect takeout.`, `Second flee. We're billing cardio in crumbs.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in volume.`, `Second chase. Prey with a fitness plan and no fridge left.`],
    close: [`Back in your face. Miss the crumbs?`, `Range ends. Soft teeth resume. Swarm hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still many.`, `Smoke fades. Soft teeth resume. Miss the vote?`],
    victory: [`Parliament down. Keep the crumbs. Don't keep the smug.`, `You won. Don't ghost our ghost — the fridge remembers.`],
    victoryHealed: [`You juiced and still took the vote. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory in Tunnel B. Optimistic lunch with a receipt.`],
    victoryKited: [`You kited a parliament. Crumb wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in volume.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the whip count.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Lunch down. Vote updated. Crumbs still ours — panic pending.`, `Verified snack. Tunnel solved. Your bag was mid.`],
    defeatCrit: [`You crit the quorum and still died. Talent without crumbs.`, `Crit energy, snack ending. Classic fridge romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Parliament writes that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Leave lunch next time.`],
  },

  'drain-gang': {
    open: [
      [`Not the crumb rats. We're the franchise. Bigger bodies, meaner landlords.`, `Cute enough you hesitate — hesitation is the royalty fee. Territory maps in grit.`],
      [`Soft ankles. Picnics. Rivals to outnumber. Grate rights in writing.`, `Pack tactics. Street cred. Franchise fees. Hygiene we don't discuss.`],
      [`Cats. Bleach. Flame. Mystery shoppers in hard hats — turn-offs. You smell like ankles. Perfect.`, `Conspiracy under the street: every overflow is a storefront. You're window shopping wrong.`],
      [`Shocking honesty: we put our name on the map in grit. Soft launch your pride into the grate.`, `Sweet of you to hesitate without being asked. Keep hesitating. Royalty accrues.`],
    ],
    hit: [
      [`You scratched the franchise. Rude mid-fee.`, `That one had feelings. Landlord resentments pending.`],
      [`Gang took a nick. Grate still holds.`, `Ow. The grit remembers. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep hesitating — fees update live.`, `Bloodied franchise. Still branded. Still mean.`],
    ],
    miss: [
      [`Missed the brand. Royalty continues.`, `Air through the grate. Try again with intent — or soft ankles.`],
      [`You swung at Overflow Franchisees and hit a map. Maps bite back in grit.`, `Miss logged. Territory unchanged.`],
    ],
    crit: [
      [`That one tore the brand. Emotionally. And also actually.`, `Crit on the franchise? Someone on the grate just flinched in grit.`],
      [`Okay. Soft spot under the landlord energy. Dangerous shopping.`, `You found the fee under the cute. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a franchise that taxes first.`, `Toxin on grate-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Overflow blooms. Flame is a turn-off and a war.`, `Arson mid-fee. Hot. Illegal. Intimate. Still branded.`],
      caltrops: [`Iron teeth. Ankles on the menu — our specialty.`, `You seeded spite. Franchises walk it in grit.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under street honesty.`, `Chemistry thrown like a drink on a royalty fee. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a grate smells like panic and bleach — another turn-off.`, `Church water on landlords. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your picnic through the haze.`, `You hid mid-fee. Franchises find soft ankles in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a franchise. Irony is a royalty.`, `Bear-trap for grate prey. We invented commitment issues with maps.`],
      net: [`Mesh on a brand. Commitment layered on grit. Flail is the fee.`, `You bagged the gang. Bold. The grate is laughing.`],
      'healing-potion': [`Red sip. Juice for picnickers who plan to live. We prefer you rare and hesitant.`, `Healing mid-fee. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Boots lose traction — we like that.`, `Slippery warfare on the grate. Career move for ankles.`],
    },
    kitGeneric: [`You opened the bag mid-fee. That's a write-up in grit.`, `Props. Theater kid. Franchise grades performances in hesitation.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Royalty noticed.`, `Flee, then kit. Grates grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our brand.`, `Runner with a finishing move. Impressed. Offended. Still collecting.`],
    mHit: [`Fee applied. Don't look surprised — you matched first.`, `That's for the unread map and the hesitation you promised.`],
    mHitBloodied: [`Bloodied and still landing. Franchise talks.`, `We're hurt. You're hurt more. Fair trade in grit.`],
    mMiss: [`Missed. Don't get cocky — the brand is still circling.`, `Lucky. Luck expires when landlords get bored.`],
    winded: [`First scratch on the franchise. Don't get attached.`, `That tickled. Upgrade your intent or hesitate properly.`],
    bruised: [`Color coming in under grit. Keep painting.`, `Mid-fee damage. Persistent — like a bad mystery shopper.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Fee continues.`, `Bloodied gang. Finish it or become décor on the grate.`],
    heartWound: [`That one landed on something soft under the landlord energy we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and taxable.`],
    run: [`Flee the grate? We invented chase in overflow.`, `Break contact? Franchises don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and soft ankles.`, `You ran twice. The map logged it. Chase is collection.`],
    chase: [`You ran twice. Chase is how franchises collect royalty.`, `Second flee. We're billing cardio in grit.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in fees.`, `Second chase. Prey with a fitness plan and no ankles left.`],
    close: [`Back in your face. Miss the grate?`, `Range ends. Soft teeth resume. Franchise hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still branded.`, `Smoke fades. Soft teeth resume. Miss the fee?`],
    victory: [`Franchise down. Keep the map. Don't keep the smug.`, `You won. Don't ghost our ghost — the grit remembers.`],
    victoryHealed: [`You juiced and still took the fee. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory on the grate. Optimistic picnic with a receipt.`],
    victoryKited: [`You kited a franchise. Landlord wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in grit.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the royalty.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Picnic down. Fee updated. Brand's still ours — ankles pending.`, `Verified snack. Grate solved. Your bag was mid.`],
    defeatCrit: [`You crit the franchise and still died. Talent without hesitation.`, `Crit energy, snack ending. Classic overflow romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Maps write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Hesitate next time.`],
  },

  'scrap-mob': {
    open: [
      [`Patches kept a private ledger. We keep a picket. Volume is theology; dues payable in shinies.`, `Cross the line and find out what collective means with knives.`],
      [`A fight we can surround. Loot to argue over. Fair dues. No scabs.`, `Nimble escape. Too many knives. Union energy. Signs you can read in the dark.`],
      [`Taxes. Solo heroes. "Just goblins." Anyone crossing the picket — turn-offs. You smell like a scab. Prove us wrong.`, `We vote to thrash. Motion carries. Bargaining unit: teeth.`],
      [`Shocking honesty: Patches kept secrets; we keep volume — and each other.`, `Sweet of you to thrash without being asked. Keep thrashing. The dump likes the noise.`],
    ],
    hit: [
      [`You scratched the local. Rude mid-picket.`, `That one had feelings. Union resentments pending.`],
      [`Mob took a nick. Line still holds.`, `Ow. The shinies remember. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep crossing — dues update live.`, `Bloodied local. Still surrounding. Still loud.`],
    ],
    miss: [
      [`Missed the picket. Vote continues.`, `Air through Mutual Aid Dump. Try again with intent — or pay dues.`],
      [`You swung at Local 666 and hit a sign. Signs bite back in unison.`, `Miss logged. Line unchanged.`],
    ],
    crit: [
      [`That one tore the line. Emotionally. And also actually.`, `Crit on the union? Someone on the picket just flinched in shinies.`],
      [`Okay. Soft spot under the volume. Dangerous scabbing.`, `You found the mutual aid under the knives. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned a local that surrounds first.`, `Toxin on picket-adjacent dates. Cute. Our blood is shared and unimpressed.`],
      'alchemists-fire': [`Flask hits. Dump blooms. Fire hates mutual aid — we hate fire more.`, `Arson mid-picket. Hot. Illegal. Intimate. Still surrounding.`],
      caltrops: [`Iron teeth. Ankles on the menu. We surround for a living.`, `You seeded spite. Locals walk it in volume.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under dump honesty.`, `Chemistry thrown like a drink on dues. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a picket smells like panic and bleach.`, `Church water on goblins. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your scab energy through the haze.`, `You hid mid-picket. Locals find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a union. Irony is a dues joke.`, `Bear-trap for dump prey. We invented commitment issues with signs.`],
      net: [`Mesh on many. Commitment layered on volume. Flail is the motion.`, `You bagged the local. Bold. The picket is laughing.`],
      'healing-potion': [`Red sip. Juice for scabs who plan to live. We prefer you rare and surrounded.`, `Healing mid-picket. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Lines slip for no one.`, `Slippery warfare in Mutual Aid Dump. Career move for a scab.`],
    },
    kitGeneric: [`You opened the bag mid-picket. That's a write-up in shinies.`, `Props. Theater kid. Local 666 grades performances in volume.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Scab energy.`, `Flee, then kit. Pickets grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our line.`, `Runner with a finishing move. Impressed. Offended. Still surrounding.`],
    mHit: [`Surround applied. Don't look surprised — you matched first.`, `That's for the unread dues and the cross you promised.`],
    mHitBloodied: [`Bloodied and still landing. Volume talks.`, `We're hurt. You're hurt more. Fair trade in shinies.`],
    mMiss: [`Missed. Don't get cocky — the local is still circling.`, `Lucky. Luck expires when unions get bored.`],
    winded: [`First scratch on the picket. Don't get attached.`, `That tickled. Upgrade your intent or pay dues.`],
    bruised: [`Color coming in under scrap. Keep painting.`, `Mid-picket damage. Persistent — like a bad solo hero.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Vote continues.`, `Bloodied mob. Finish it or become décor on the line.`],
    heartWound: [`That one landed on something soft under the volume we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and collective.`],
    run: [`Flee the dump? We invented chase as a surround.`, `Break contact? Pickets don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and scab energy.`, `You ran twice. The local logged it. Chase is enforcement.`],
    chase: [`You ran twice. Chase is how locals collect dues.`, `Second flee. We're billing cardio in shinies.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in volume.`, `Second chase. Prey with a fitness plan and no line left.`],
    close: [`Back in your face. Miss the picket?`, `Range ends. Soft knives resume. Mob hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still surrounding.`, `Smoke fades. Soft knives resume. Miss the dues?`],
    victory: [`Local down. Keep the shinies. Don't keep the smug.`, `You won. Don't ghost our ghost — the picket remembers.`],
    victoryHealed: [`You juiced and still took the line. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory at the dump. Optimistic scab with a receipt.`],
    victoryKited: [`You kited Local 666. Union wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in volume.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the dues.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Scab down. Dues updated. Line's still ours — loot pending.`, `Verified snack. Dump solved. Your bag was mid.`],
    defeatCrit: [`You crit the local and still died. Talent without dues.`, `Crit energy, snack ending. Classic picket romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Signs write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Pay dues next time.`],
  },

  clickers: {
    open: [
      [`We click before we drink. We leave a receipt you can't read in the dark.`, `Tip is theoretical; the soundtrack is not. After-hours service with needles.`],
      [`Exposed skin. High places. Bad sleep. Guests who forget to tip — we remember in the dark.`, `Volume. Needles. A horrible harmony. Graveyard-shift charm.`],
      [`Nets. Wind magic. Repellent. Daylight savings — turn-offs. You smell like warmth. Perfect.`, `Soft tip in blood is classy. Hard tip in screams is memorable. Choose branding.`],
      [`Shocking honesty: neon nests remember who never tipped. Conspiracy of receipts you can't read.`, `Sweet of you to thrash without being asked. Keep thrashing. Roof vents like the applause.`],
    ],
    hit: [
      [`You scratched hospitality. Rude mid-click.`, `That one had feelings. Tip resentments pending.`],
      [`Overhead took a nick. Soundtrack still holds.`, `Ow. The vents remember. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep tipping — service updates live.`, `Bloodied hospitality. Still clicking. Still charming.`],
    ],
    miss: [
      [`Missed the click. Service continues.`, `Air through roof vents. Try again with intent — or tip.`],
      [`You swung at Night Shift and hit a receipt. Receipts bite back in dark.`, `Miss logged. Soundtrack unchanged.`],
    ],
    crit: [
      [`That one tore the harmony. Emotionally. And also actually.`, `Crit on hospitality? Someone in the vents just flinched on time-and-a-half.`],
      [`Okay. Soft spot under the click. Dangerous tipping.`, `You found the needle under the charm. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned hospitality that drinks first.`, `Toxin on tip-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Vents bloom. Fire hates nests — we hate fire more.`, `Arson mid-service. Hot. Illegal. Intimate. Still clicking.`],
      caltrops: [`Iron teeth. Ankles on the menu. We prefer high places.`, `You seeded spite. Hospitality walks it in volume.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under neon honesty.`, `Chemistry thrown like a drink on a tip. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith in vents smells like panic and bleach.`, `Church water on bats. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your warmth through the haze.`, `You hid mid-click. Hospitality finds soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a tip. Irony is a receipt.`, `Bear-trap for vent prey. We invented commitment issues with needles.`],
      net: [`Mesh — our turn-off, your prop. Commitment with holes.`, `You bagged hospitality. Bold. Nets preferred unless they're yours.`],
      'healing-potion': [`Red sip. Juice for guests who plan to live. We prefer you rare and tipping.`, `Healing mid-service. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Soundtrack slips for no one.`, `Slippery warfare on the roof. Career move for a bad tipper.`],
    },
    kitGeneric: [`You opened the bag mid-click. That's a write-up in receipts.`, `Props. Theater kid. Hospitality grades performances in screams.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Tip forgotten.`, `Flee, then kit. Vents grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our click.`, `Runner with a finishing move. Impressed. Offended. Still serving.`],
    mHit: [`Needle applied. Don't look surprised — you matched first.`, `That's for the unread tip and the scream you promised.`],
    mHitBloodied: [`Bloodied and still landing. Volume talks.`, `We're hurt. You're hurt more. Fair trade in blood tips.`],
    mMiss: [`Missed. Don't get cocky — the click is still circling.`, `Lucky. Luck expires when hospitality gets bored.`],
    winded: [`First scratch on the soundtrack. Don't get attached.`, `That tickled. Upgrade your intent or tip properly.`],
    bruised: [`Color coming in under wing. Keep painting.`, `Mid-service damage. Persistent — like a bad tip.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Service continues.`, `Bloodied overhead. Finish it or become décor in the vents.`],
    heartWound: [`That one landed on something soft under the charm we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and tippable.`],
    run: [`Flee the vents? We invented chase as applause.`, `Break contact? Hospitality doesn't do rain checks.`],
    runAgain: [`Second escape. Prey with legs and no tip.`, `You ran twice. The receipt logged it. Chase is service recovery.`],
    chase: [`You ran twice. Chase is how bats collect tips.`, `Second flee. We're billing cardio in screams.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in clicks.`, `Second chase. Prey with a fitness plan and no tip left.`],
    close: [`Back in your face. Miss the click?`, `Range ends. Soft needles resume. Hospitality hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still clicking.`, `Smoke fades. Soft needles resume. Miss the tip?`],
    victory: [`Hospitality down. Keep the receipt. Don't keep the smug.`, `You won. Don't ghost our ghost — the vents remember.`],
    victoryHealed: [`You juiced and still took the tip. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory on the roof. Optimistic guest with a receipt.`],
    victoryKited: [`You kited Night Shift. Hospitality wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in volume.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the tip.`],
    victoryNet: [`You bagged us and finished the job. Our turn-off became your ending.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Guest down. Tip updated. Click's still ours — scream pending.`, `Verified snack. Vents solved. Your bag was mid.`],
    defeatCrit: [`You crit hospitality and still died. Talent without a tip.`, `Crit energy, snack ending. Classic graveyard romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Receipts write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Tip next time.`],
  },

  'laugh-track': {
    open: [
      [`We laugh when you fall. Then we bite. Then we laugh like the show never stopped.`, `Your scream is the only rating that matters — we are the audience that eats.`],
      [`Prey that makes a soundtrack. Rivals who bleed on camera. Content.`, `Rampage. Spears. A chorus you can't mute. Bait with teeth.`],
      [`Silence spells. High walls. People who don't get the joke. Ad blockers — turn-offs. You look funny. Perfect.`, `Ha — no, that's the track. Real pain's quieter. Then we bite.`],
      [`Shocking honesty: we replay your scream. Anything that goes viral is dinner.`, `Sweet of you to thrash without being asked. Keep thrashing. The abattoir likes the ratings.`],
    ],
    hit: [
      [`You scratched the audience. Rude mid-laugh.`, `That one had feelings. Rating resentments pending.`],
      [`Track took a nick. Chorus still holds.`, `Ow. The underpass remembers. So do we.`],
    ],
    hitBloodied: [
      [`We're leaking. Keep screaming — ratings update live.`, `Bloodied audience. Still laughing. Still biting.`],
    ],
    miss: [
      [`Missed the joke. Show continues.`, `Air through Abattoir Underpass. Try again with intent — or fall funnier.`],
      [`You swung at the studio audience and hit a laugh. Laughs bite back.`, `Miss logged. Track unchanged.`],
    ],
    crit: [
      [`That one tore the chorus. Emotionally. And also actually.`, `Crit on the audience? Someone in the underpass just flinched on camera.`],
      [`Okay. Soft spot under the laugh. Dangerous content.`, `You found the bite under the track. Keep going — we're listening.`],
    ],
    kits: {
      poison: [`Green sheen. You seasoned an audience that eats first.`, `Toxin on scream-adjacent dates. Cute. Our blood quit caring about chemistry.`],
      'alchemists-fire': [`Flask hits. Underpass blooms. Fire hates ratings — we hate fire more.`, `Arson mid-show. Hot. Illegal. Intimate. Still laughing.`],
      caltrops: [`Iron teeth. Ankles on the menu. We chase for a living.`, `You seeded spite. Audiences walk it in rampage.`],
      'acid-vial': [`Acid kiss. Your face is the real spill under camera honesty.`, `Chemistry thrown like a drink on a scream. Sticky. Personal.`],
      'holy-water': [`Blessed tap. Faith on a laugh track smells like panic and bleach.`, `Church water on hyenas. The dead hate the brand. We just hate the wet.`],
      smokestick: [`Gray bloom. Fog cosplay. We still smell your scream through the haze.`, `You hid mid-show. Audiences find soft prey in dark.`],
      'hunting-trap': [`Iron jaws. You trapped a rating. Irony is a punchline.`, `Bear-trap for underpass prey. We invented commitment issues with spears.`],
      net: [`Mesh on a chorus. Commitment layered on laughs. Flail is the content.`, `You bagged the audience. Bold. The track is laughing.`],
      'healing-potion': [`Red sip. Juice for prey who plan to live. We prefer you rare and screaming.`, `Healing mid-show. Soft. Optimistic. Delicious.`],
      'oil-flask': [`Oil sheets. Greasy riders. Ratings slip for no one.`, `Slippery warfare under the abattoir. Career move for content.`],
    },
    kitGeneric: [`You opened the bag mid-laugh. That's a write-up in screams.`, `Props. Theater kid. Studio audience grades performances in blood.`],
    kitRan: [`You ran then dug in the bag. Cowardice with props. Funny.`, `Flee, then kit. Tracks grade that soft.`],
    hcritRan: [`You fled then crit. Soft runner into a hard landing on our laugh.`, `Runner with a finishing move. Impressed. Offended. Still biting.`],
    mHit: [`Bite applied. Don't look surprised — you matched first.`, `That's for the unread scream and the fall you promised.`],
    mHitBloodied: [`Bloodied and still landing. Ratings talk.`, `We're hurt. You're hurt more. Fair trade in screams.`],
    mMiss: [`Missed. Don't get cocky — the track is still circling.`, `Lucky. Luck expires when audiences get bored.`],
    winded: [`First scratch on the chorus. Don't get attached.`, `That tickled. Upgrade your intent or fall funnier.`],
    bruised: [`Color coming in under fur. Keep painting.`, `Mid-show damage. Persistent — like a bad ad blocker.`],
    bloodied: [`We're leaking. You're still soft. Fix one. Show continues.`, `Bloodied audience. Finish it or become décor on the track.`],
    heartWound: [`That one landed on something soft under the laugh we weren't advertising.`, `Don't look at us like that while you're winning. It's rude and viral.`],
    run: [`Flee the underpass? We invented chase as content.`, `Break contact? Shows don't do rain checks.`],
    runAgain: [`Second escape. Prey with legs — great B-roll.`, `You ran twice. The track logged it. Chase is programming.`],
    chase: [`You ran twice. Chase is how audiences collect screams.`, `Second flee. We're billing cardio in laughs.`],
    chase2: [`Ran twice. Chase twice. Love language confirmed in ratings.`, `Second chase. Prey with a fitness plan and no joke left.`],
    close: [`Back in your face. Miss the laugh?`, `Range ends. Soft teeth resume. Audience hugs harder.`],
    closeSmoke: [`Closing through your fog. Cute prop. Still laughing.`, `Smoke fades. Soft teeth resume. Miss the scream?`],
    victory: [`Audience down. Keep the scream. Don't keep the smug.`, `You won. Don't ghost our ghost — the track remembers.`],
    victoryHealed: [`You juiced and still took the rating. Soft. Effective. Almost respectable cowardice.`, `Healing potion victory under the abattoir. Optimistic content with a receipt.`],
    victoryKited: [`You kited the studio audience. Punchline wisdom undone by jogging.`, `Ran us ragged then finished it. Cardio is a war crime in laughs.`],
    victoryCrit: [`You crit your way to the end. Claws and closure.`, `Crit path victory. Ugly. Clean. Don't get soft about the scream.`],
    victoryNet: [`You bagged us and finished the job. Commitment issues resolved.`, `Net plus win. Soft bag into a hard ending.`],
    defeat: [`Prey down. Rating updated. Laugh's still ours — scream pending.`, `Verified snack. Underpass solved. Your bag was mid.`],
    defeatCrit: [`You crit the audience and still died. Talent without a punchline.`, `Crit energy, snack ending. Classic studio romance.`],
    defeatRan: [`You ran and still died. Cardio without a plan.`, `Fleeing into a snack ending. Tracks write that joke often.`],
    defeatHeal: [`You juiced and still went down. Optimistic snack.`, `Healing potion, then dirt. Soft. Memorable. Fall funnier next time.`],
  },
};
